UPDATE D240_municipio SET suscripcion = 1101 WHERE territorio = 'Iquique';
UPDATE D240_municipio SET suscripcion = 1107 WHERE territorio = 'Alto Hospicio';
UPDATE D240_municipio SET suscripcion = 1401 WHERE territorio = 'Pozo Almonte';
UPDATE D240_municipio SET suscripcion = 1402 WHERE territorio = 'Camiña';
UPDATE D240_municipio SET suscripcion = 1403 WHERE territorio = 'Colchane';
UPDATE D240_municipio SET suscripcion = 1404 WHERE territorio = 'Huara';
UPDATE D240_municipio SET suscripcion = 1405 WHERE territorio = 'Pica';
UPDATE D240_municipio SET suscripcion = 2101 WHERE territorio = 'Antofagasta';
UPDATE D240_municipio SET suscripcion = 2102 WHERE territorio = 'Mejillones';
UPDATE D240_municipio SET suscripcion = 2103 WHERE territorio = 'Sierra Gorda';
UPDATE D240_municipio SET suscripcion = 2104 WHERE territorio = 'Taltal';
UPDATE D240_municipio SET suscripcion = 2201 WHERE territorio = 'Calama';
UPDATE D240_municipio SET suscripcion = 2202 WHERE territorio = 'Ollagüe';
UPDATE D240_municipio SET suscripcion = 2203 WHERE territorio = 'San Pedro de Atacama';
UPDATE D240_municipio SET suscripcion = 2301 WHERE territorio = 'Tocopilla';
UPDATE D240_municipio SET suscripcion = 2302 WHERE territorio = 'María Elena';
UPDATE D240_municipio SET suscripcion = 3101 WHERE territorio = 'Copiapó';
UPDATE D240_municipio SET suscripcion = 3102 WHERE territorio = 'Caldera';
UPDATE D240_municipio SET suscripcion = 3103 WHERE territorio = 'Tierra Amarilla';
UPDATE D240_municipio SET suscripcion = 3201 WHERE territorio = 'Chañaral';
UPDATE D240_municipio SET suscripcion = 3202 WHERE territorio = 'Diego de Almagro';
UPDATE D240_municipio SET suscripcion = 3301 WHERE territorio = 'Vallenar';
UPDATE D240_municipio SET suscripcion = 3302 WHERE territorio = 'Alto del Carmen';
UPDATE D240_municipio SET suscripcion = 3303 WHERE territorio = 'Freirina';
UPDATE D240_municipio SET suscripcion = 3304 WHERE territorio = 'Huasco';
UPDATE D240_municipio SET suscripcion = 4101 WHERE territorio = 'La Serena';
UPDATE D240_municipio SET suscripcion = 4102 WHERE territorio = 'Coquimbo';
UPDATE D240_municipio SET suscripcion = 4103 WHERE territorio = 'Andacollo';
UPDATE D240_municipio SET suscripcion = 4104 WHERE territorio = 'La Higuera';
UPDATE D240_municipio SET suscripcion = 4105 WHERE territorio = 'Paiguano';
UPDATE D240_municipio SET suscripcion = 4106 WHERE territorio = 'Vicuña';
UPDATE D240_municipio SET suscripcion = 4201 WHERE territorio = 'Illapel';
UPDATE D240_municipio SET suscripcion = 4202 WHERE territorio = 'Canela';
UPDATE D240_municipio SET suscripcion = 4203 WHERE territorio = 'Los Vilos';
UPDATE D240_municipio SET suscripcion = 4204 WHERE territorio = 'Salamanca';
UPDATE D240_municipio SET suscripcion = 4301 WHERE territorio = 'Ovalle';
UPDATE D240_municipio SET suscripcion = 4302 WHERE territorio = 'Combarbalá';
UPDATE D240_municipio SET suscripcion = 4303 WHERE territorio = 'Monte Patria';
UPDATE D240_municipio SET suscripcion = 4304 WHERE territorio = 'Punitaqui';
UPDATE D240_municipio SET suscripcion = 4305 WHERE territorio = 'Río Hurtado';
UPDATE D240_municipio SET suscripcion = 5101 WHERE territorio = 'Valparaíso';
UPDATE D240_municipio SET suscripcion = 5102 WHERE territorio = 'Casablanca';
UPDATE D240_municipio SET suscripcion = 5103 WHERE territorio = 'Concón';
UPDATE D240_municipio SET suscripcion = 5104 WHERE territorio = 'Juan Fernández';
UPDATE D240_municipio SET suscripcion = 5105 WHERE territorio = 'Puchuncaví';
UPDATE D240_municipio SET suscripcion = 5107 WHERE territorio = 'Quintero';
UPDATE D240_municipio SET suscripcion = 5109 WHERE territorio = 'Viña del Mar';
UPDATE D240_municipio SET suscripcion = 5201 WHERE territorio = 'Isla de Pascua';
UPDATE D240_municipio SET suscripcion = 5301 WHERE territorio = 'Los Andes';
UPDATE D240_municipio SET suscripcion = 5302 WHERE territorio = 'Calle Larga';
UPDATE D240_municipio SET suscripcion = 5303 WHERE territorio = 'Rinconada';
UPDATE D240_municipio SET suscripcion = 5304 WHERE territorio = 'San Esteban';
UPDATE D240_municipio SET suscripcion = 5401 WHERE territorio = 'La Ligua';
UPDATE D240_municipio SET suscripcion = 5402 WHERE territorio = 'Cabildo';
UPDATE D240_municipio SET suscripcion = 5403 WHERE territorio = 'Papudo';
UPDATE D240_municipio SET suscripcion = 5404 WHERE territorio = 'Petorca';
UPDATE D240_municipio SET suscripcion = 5405 WHERE territorio = 'Zapallar';
UPDATE D240_municipio SET suscripcion = 5501 WHERE territorio = 'Quillota';
UPDATE D240_municipio SET suscripcion = 5502 WHERE territorio = 'Calera';
UPDATE D240_municipio SET suscripcion = 5503 WHERE territorio = 'Hijuelas';
UPDATE D240_municipio SET suscripcion = 5504 WHERE territorio = 'La Cruz';
UPDATE D240_municipio SET suscripcion = 5506 WHERE territorio = 'Nogales';
UPDATE D240_municipio SET suscripcion = 5601 WHERE territorio = 'San Antonio';
UPDATE D240_municipio SET suscripcion = 5602 WHERE territorio = 'Algarrobo';
UPDATE D240_municipio SET suscripcion = 5603 WHERE territorio = 'Cartagena';
UPDATE D240_municipio SET suscripcion = 5604 WHERE territorio = 'El Quisco';
UPDATE D240_municipio SET suscripcion = 5605 WHERE territorio = 'El Tabo';
UPDATE D240_municipio SET suscripcion = 5606 WHERE territorio = 'Santo Domingo';
UPDATE D240_municipio SET suscripcion = 5701 WHERE territorio = 'San Felipe';
UPDATE D240_municipio SET suscripcion = 5702 WHERE territorio = 'Catemu';
UPDATE D240_municipio SET suscripcion = 5703 WHERE territorio = 'Llaillay';
UPDATE D240_municipio SET suscripcion = 5704 WHERE territorio = 'Panquehue';
UPDATE D240_municipio SET suscripcion = 5705 WHERE territorio = 'Putaendo';
UPDATE D240_municipio SET suscripcion = 5706 WHERE territorio = 'Santa María';
UPDATE D240_municipio SET suscripcion = 5801 WHERE territorio = 'Quilpué';
UPDATE D240_municipio SET suscripcion = 5802 WHERE territorio = 'Limache';
UPDATE D240_municipio SET suscripcion = 5803 WHERE territorio = 'Olmué';
UPDATE D240_municipio SET suscripcion = 5804 WHERE territorio = 'Villa Alemana';
UPDATE D240_municipio SET suscripcion = 6101 WHERE territorio = 'Rancagua';
UPDATE D240_municipio SET suscripcion = 6102 WHERE territorio = 'Codegua';
UPDATE D240_municipio SET suscripcion = 6103 WHERE territorio = 'Coinco';
UPDATE D240_municipio SET suscripcion = 6104 WHERE territorio = 'Coltauco';
UPDATE D240_municipio SET suscripcion = 6105 WHERE territorio = 'Doñihue';
UPDATE D240_municipio SET suscripcion = 6106 WHERE territorio = 'Graneros';
UPDATE D240_municipio SET suscripcion = 6107 WHERE territorio = 'Las Cabras';
UPDATE D240_municipio SET suscripcion = 6108 WHERE territorio = 'Machalí';
UPDATE D240_municipio SET suscripcion = 6109 WHERE territorio = 'Malloa';
UPDATE D240_municipio SET suscripcion = 6110 WHERE territorio = 'Mostazal';
UPDATE D240_municipio SET suscripcion = 6111 WHERE territorio = 'Olivar';
UPDATE D240_municipio SET suscripcion = 6112 WHERE territorio = 'Peumo';
UPDATE D240_municipio SET suscripcion = 6113 WHERE territorio = 'Pichidegua';
UPDATE D240_municipio SET suscripcion = 6114 WHERE territorio = 'Quinta de Tilcoco';
UPDATE D240_municipio SET suscripcion = 6115 WHERE territorio = 'Rengo';
UPDATE D240_municipio SET suscripcion = 6116 WHERE territorio = 'Requínoa';
UPDATE D240_municipio SET suscripcion = 6117 WHERE territorio = 'San Vicente';
UPDATE D240_municipio SET suscripcion = 6201 WHERE territorio = 'Pichilemu';
UPDATE D240_municipio SET suscripcion = 6202 WHERE territorio = 'La Estrella';
UPDATE D240_municipio SET suscripcion = 6203 WHERE territorio = 'Litueche';
UPDATE D240_municipio SET suscripcion = 6204 WHERE territorio = 'Marchihue';
UPDATE D240_municipio SET suscripcion = 6205 WHERE territorio = 'Navidad';
UPDATE D240_municipio SET suscripcion = 6206 WHERE territorio = 'Paredones';
UPDATE D240_municipio SET suscripcion = 6301 WHERE territorio = 'San Fernando';
UPDATE D240_municipio SET suscripcion = 6302 WHERE territorio = 'Chépica';
UPDATE D240_municipio SET suscripcion = 6303 WHERE territorio = 'Chimbarongo';
UPDATE D240_municipio SET suscripcion = 6304 WHERE territorio = 'Lolol';
UPDATE D240_municipio SET suscripcion = 6305 WHERE territorio = 'Nancagua';
UPDATE D240_municipio SET suscripcion = 6306 WHERE territorio = 'Palmilla';
UPDATE D240_municipio SET suscripcion = 6307 WHERE territorio = 'Peralillo';
UPDATE D240_municipio SET suscripcion = 6308 WHERE territorio = 'Placilla';
UPDATE D240_municipio SET suscripcion = 6309 WHERE territorio = 'Pumanque';
UPDATE D240_municipio SET suscripcion = 6310 WHERE territorio = 'Santa Cruz';
UPDATE D240_municipio SET suscripcion = 7101 WHERE territorio = 'Talca';
UPDATE D240_municipio SET suscripcion = 7102 WHERE territorio = 'Constitución';
UPDATE D240_municipio SET suscripcion = 7103 WHERE territorio = 'Curepto';
UPDATE D240_municipio SET suscripcion = 7104 WHERE territorio = 'Empedrado';
UPDATE D240_municipio SET suscripcion = 7105 WHERE territorio = 'Maule';
UPDATE D240_municipio SET suscripcion = 7106 WHERE territorio = 'Pelarco';
UPDATE D240_municipio SET suscripcion = 7107 WHERE territorio = 'Pencahue';
UPDATE D240_municipio SET suscripcion = 7108 WHERE territorio = 'Río Claro';
UPDATE D240_municipio SET suscripcion = 7109 WHERE territorio = 'San Clemente';
UPDATE D240_municipio SET suscripcion = 7110 WHERE territorio = 'San Rafael';
UPDATE D240_municipio SET suscripcion = 7201 WHERE territorio = 'Cauquenes';
UPDATE D240_municipio SET suscripcion = 7202 WHERE territorio = 'Chanco';
UPDATE D240_municipio SET suscripcion = 7203 WHERE territorio = 'Pelluhue';
UPDATE D240_municipio SET suscripcion = 7301 WHERE territorio = 'Curicó';
UPDATE D240_municipio SET suscripcion = 7302 WHERE territorio = 'Hualañé';
UPDATE D240_municipio SET suscripcion = 7303 WHERE territorio = 'Licantén';
UPDATE D240_municipio SET suscripcion = 7304 WHERE territorio = 'Molina';
UPDATE D240_municipio SET suscripcion = 7305 WHERE territorio = 'Rauco';
UPDATE D240_municipio SET suscripcion = 7306 WHERE territorio = 'Romeral';
UPDATE D240_municipio SET suscripcion = 7307 WHERE territorio = 'Sagrada Familia';
UPDATE D240_municipio SET suscripcion = 7308 WHERE territorio = 'Teno';
UPDATE D240_municipio SET suscripcion = 7309 WHERE territorio = 'Vichuquén';
UPDATE D240_municipio SET suscripcion = 7401 WHERE territorio = 'Linares';
UPDATE D240_municipio SET suscripcion = 7402 WHERE territorio = 'Colbún';
UPDATE D240_municipio SET suscripcion = 7403 WHERE territorio = 'Longaví';
UPDATE D240_municipio SET suscripcion = 7404 WHERE territorio = 'Parral';
UPDATE D240_municipio SET suscripcion = 7405 WHERE territorio = 'Retiro';
UPDATE D240_municipio SET suscripcion = 7406 WHERE territorio = 'San Javier';
UPDATE D240_municipio SET suscripcion = 7407 WHERE territorio = 'Villa Alegre';
UPDATE D240_municipio SET suscripcion = 7408 WHERE territorio = 'Yerbas Buenas';
UPDATE D240_municipio SET suscripcion = 8101 WHERE territorio = 'Concepción';
UPDATE D240_municipio SET suscripcion = 8102 WHERE territorio = 'Coronel';
UPDATE D240_municipio SET suscripcion = 8103 WHERE territorio = 'Chiguayante';
UPDATE D240_municipio SET suscripcion = 8104 WHERE territorio = 'Florida';
UPDATE D240_municipio SET suscripcion = 8105 WHERE territorio = 'Hualqui';
UPDATE D240_municipio SET suscripcion = 8106 WHERE territorio = 'Lota';
UPDATE D240_municipio SET suscripcion = 8107 WHERE territorio = 'Penco';
UPDATE D240_municipio SET suscripcion = 8108 WHERE territorio = 'San Pedro de la Paz';
UPDATE D240_municipio SET suscripcion = 8109 WHERE territorio = 'Santa Juana';
UPDATE D240_municipio SET suscripcion = 8110 WHERE territorio = 'Talcahuano';
UPDATE D240_municipio SET suscripcion = 8111 WHERE territorio = 'Tomé';
UPDATE D240_municipio SET suscripcion = 8112 WHERE territorio = 'Hualpén';
UPDATE D240_municipio SET suscripcion = 8201 WHERE territorio = 'Lebu';
UPDATE D240_municipio SET suscripcion = 8202 WHERE territorio = 'Arauco';
UPDATE D240_municipio SET suscripcion = 8203 WHERE territorio = 'Cañete';
UPDATE D240_municipio SET suscripcion = 8204 WHERE territorio = 'Contulmo';
UPDATE D240_municipio SET suscripcion = 8205 WHERE territorio = 'Curanilahue';
UPDATE D240_municipio SET suscripcion = 8206 WHERE territorio = 'Los Alamos';
UPDATE D240_municipio SET suscripcion = 8207 WHERE territorio = 'Tirúa';
UPDATE D240_municipio SET suscripcion = 8301 WHERE territorio = 'Los Angeles';
UPDATE D240_municipio SET suscripcion = 8302 WHERE territorio = 'Antuco';
UPDATE D240_municipio SET suscripcion = 8303 WHERE territorio = 'Cabrero';
UPDATE D240_municipio SET suscripcion = 8304 WHERE territorio = 'Laja';
UPDATE D240_municipio SET suscripcion = 8305 WHERE territorio = 'Mulchén';
UPDATE D240_municipio SET suscripcion = 8306 WHERE territorio = 'Nacimiento';
UPDATE D240_municipio SET suscripcion = 8307 WHERE territorio = 'Negrete';
UPDATE D240_municipio SET suscripcion = 8308 WHERE territorio = 'Quilaco';
UPDATE D240_municipio SET suscripcion = 8309 WHERE territorio = 'Quilleco';
UPDATE D240_municipio SET suscripcion = 8310 WHERE territorio = 'San Rosendo';
UPDATE D240_municipio SET suscripcion = 8311 WHERE territorio = 'Santa Bárbara';
UPDATE D240_municipio SET suscripcion = 8312 WHERE territorio = 'Tucapel';
UPDATE D240_municipio SET suscripcion = 8313 WHERE territorio = 'Yumbel';
UPDATE D240_municipio SET suscripcion = 8314 WHERE territorio = 'Alto Biobío';
UPDATE D240_municipio SET suscripcion = 16101 WHERE territorio = 'Chillán';
UPDATE D240_municipio SET suscripcion = 16102 WHERE territorio = 'Bulnes';
UPDATE D240_municipio SET suscripcion = 16202 WHERE territorio = 'Cobquecura';
UPDATE D240_municipio SET suscripcion = 16203 WHERE territorio = 'Coelemu';
UPDATE D240_municipio SET suscripcion = 16302 WHERE territorio = 'Coihueco';
UPDATE D240_municipio SET suscripcion = 16103 WHERE territorio = 'Chillán Viejo';
UPDATE D240_municipio SET suscripcion = 16104 WHERE territorio = 'El Carmen';
UPDATE D240_municipio SET suscripcion = 16204 WHERE territorio = 'Ninhue';
UPDATE D240_municipio SET suscripcion = 16303 WHERE territorio = 'Ñiquén';
UPDATE D240_municipio SET suscripcion = 16105 WHERE territorio = 'Pemuco';
UPDATE D240_municipio SET suscripcion = 16106 WHERE territorio = 'Pinto';
UPDATE D240_municipio SET suscripcion = 16205 WHERE territorio = 'Portezuelo';
UPDATE D240_municipio SET suscripcion = 16107 WHERE territorio = 'Quillón';
UPDATE D240_municipio SET suscripcion = 16201 WHERE territorio = 'Quirihue';
UPDATE D240_municipio SET suscripcion = 16206 WHERE territorio = 'Ránquil';
UPDATE D240_municipio SET suscripcion = 16301 WHERE territorio = 'San Carlos';
UPDATE D240_municipio SET suscripcion = 16304 WHERE territorio = 'San Fabián';
UPDATE D240_municipio SET suscripcion = 16108 WHERE territorio = 'San Ignacio';
UPDATE D240_municipio SET suscripcion = 16305 WHERE territorio = 'San Nicolás';
UPDATE D240_municipio SET suscripcion = 16207 WHERE territorio = 'Treguaco';
UPDATE D240_municipio SET suscripcion = 16109 WHERE territorio = 'Yungay';
UPDATE D240_municipio SET suscripcion = 9101 WHERE territorio = 'Temuco';
UPDATE D240_municipio SET suscripcion = 9102 WHERE territorio = 'Carahue';
UPDATE D240_municipio SET suscripcion = 9103 WHERE territorio = 'Cunco';
UPDATE D240_municipio SET suscripcion = 9104 WHERE territorio = 'Curarrehue';
UPDATE D240_municipio SET suscripcion = 9105 WHERE territorio = 'Freire';
UPDATE D240_municipio SET suscripcion = 9106 WHERE territorio = 'Galvarino';
UPDATE D240_municipio SET suscripcion = 9107 WHERE territorio = 'Gorbea';
UPDATE D240_municipio SET suscripcion = 9108 WHERE territorio = 'Lautaro';
UPDATE D240_municipio SET suscripcion = 9109 WHERE territorio = 'Loncoche';
UPDATE D240_municipio SET suscripcion = 9110 WHERE territorio = 'Melipeuco';
UPDATE D240_municipio SET suscripcion = 9111 WHERE territorio = 'Nueva Imperial';
UPDATE D240_municipio SET suscripcion = 9112 WHERE territorio = 'Padre las Casas';
UPDATE D240_municipio SET suscripcion = 9113 WHERE territorio = 'Perquenco';
UPDATE D240_municipio SET suscripcion = 9114 WHERE territorio = 'Pitrufquén';
UPDATE D240_municipio SET suscripcion = 9115 WHERE territorio = 'Pucón';
UPDATE D240_municipio SET suscripcion = 9116 WHERE territorio = 'Saavedra';
UPDATE D240_municipio SET suscripcion = 9117 WHERE territorio = 'Teodoro Schmidt';
UPDATE D240_municipio SET suscripcion = 9118 WHERE territorio = 'Toltén';
UPDATE D240_municipio SET suscripcion = 9119 WHERE territorio = 'Vilcún';
UPDATE D240_municipio SET suscripcion = 9120 WHERE territorio = 'Villarrica';
UPDATE D240_municipio SET suscripcion = 9121 WHERE territorio = 'Cholchol';
UPDATE D240_municipio SET suscripcion = 9201 WHERE territorio = 'Angol';
UPDATE D240_municipio SET suscripcion = 9202 WHERE territorio = 'Collipulli';
UPDATE D240_municipio SET suscripcion = 9203 WHERE territorio = 'Curacautín';
UPDATE D240_municipio SET suscripcion = 9204 WHERE territorio = 'Ercilla';
UPDATE D240_municipio SET suscripcion = 9205 WHERE territorio = 'Lonquimay';
UPDATE D240_municipio SET suscripcion = 9206 WHERE territorio = 'Los Sauces';
UPDATE D240_municipio SET suscripcion = 9207 WHERE territorio = 'Lumaco';
UPDATE D240_municipio SET suscripcion = 9208 WHERE territorio = 'Purén';
UPDATE D240_municipio SET suscripcion = 9209 WHERE territorio = 'Renaico';
UPDATE D240_municipio SET suscripcion = 9210 WHERE territorio = 'Traiguén';
UPDATE D240_municipio SET suscripcion = 9211 WHERE territorio = 'Victoria';
UPDATE D240_municipio SET suscripcion = 10101 WHERE territorio = 'Puerto Montt';
UPDATE D240_municipio SET suscripcion = 10102 WHERE territorio = 'Calbuco';
UPDATE D240_municipio SET suscripcion = 10103 WHERE territorio = 'Cochamó';
UPDATE D240_municipio SET suscripcion = 10104 WHERE territorio = 'Fresia';
UPDATE D240_municipio SET suscripcion = 10105 WHERE territorio = 'Frutillar';
UPDATE D240_municipio SET suscripcion = 10106 WHERE territorio = 'Los Muermos';
UPDATE D240_municipio SET suscripcion = 10107 WHERE territorio = 'Llanquihue';
UPDATE D240_municipio SET suscripcion = 10108 WHERE territorio = 'Maullín';
UPDATE D240_municipio SET suscripcion = 10109 WHERE territorio = 'Puerto Varas';
UPDATE D240_municipio SET suscripcion = 10201 WHERE territorio = 'Castro';
UPDATE D240_municipio SET suscripcion = 10202 WHERE territorio = 'Ancud';
UPDATE D240_municipio SET suscripcion = 10203 WHERE territorio = 'Chonchi';
UPDATE D240_municipio SET suscripcion = 10204 WHERE territorio = 'Curaco de Vélez';
UPDATE D240_municipio SET suscripcion = 10205 WHERE territorio = 'Dalcahue';
UPDATE D240_municipio SET suscripcion = 10206 WHERE territorio = 'Puqueldón';
UPDATE D240_municipio SET suscripcion = 10207 WHERE territorio = 'Queilén';
UPDATE D240_municipio SET suscripcion = 10208 WHERE territorio = 'Quellón';
UPDATE D240_municipio SET suscripcion = 10209 WHERE territorio = 'Quemchi';
UPDATE D240_municipio SET suscripcion = 10210 WHERE territorio = 'Quinchao';
UPDATE D240_municipio SET suscripcion = 10301 WHERE territorio = 'Osorno';
UPDATE D240_municipio SET suscripcion = 10302 WHERE territorio = 'Puerto Octay';
UPDATE D240_municipio SET suscripcion = 10303 WHERE territorio = 'Purranque';
UPDATE D240_municipio SET suscripcion = 10304 WHERE territorio = 'Puyehue';
UPDATE D240_municipio SET suscripcion = 10305 WHERE territorio = 'Río Negro';
UPDATE D240_municipio SET suscripcion = 10306 WHERE territorio = 'San Juan de La Costa';
UPDATE D240_municipio SET suscripcion = 10307 WHERE territorio = 'San Pablo';
UPDATE D240_municipio SET suscripcion = 10401 WHERE territorio = 'Chaitén';
UPDATE D240_municipio SET suscripcion = 10402 WHERE territorio = 'Futaleufú';
UPDATE D240_municipio SET suscripcion = 10403 WHERE territorio = 'Hualaihué';
UPDATE D240_municipio SET suscripcion = 10404 WHERE territorio = 'Palena';
UPDATE D240_municipio SET suscripcion = 11101 WHERE territorio = 'Coihaique';
UPDATE D240_municipio SET suscripcion = 11102 WHERE territorio = 'Lago Verde';
UPDATE D240_municipio SET suscripcion = 11201 WHERE territorio = 'Aisén';
UPDATE D240_municipio SET suscripcion = 11202 WHERE territorio = 'Cisnes';
UPDATE D240_municipio SET suscripcion = 11203 WHERE territorio = 'Guaitecas';
UPDATE D240_municipio SET suscripcion = 11301 WHERE territorio = 'Cochrane';
UPDATE D240_municipio SET suscripcion = 11302 WHERE territorio = 'Villa O Higgins';
UPDATE D240_municipio SET suscripcion = 11303 WHERE territorio = 'Tortel';
UPDATE D240_municipio SET suscripcion = 11401 WHERE territorio = 'Chile Chico';
UPDATE D240_municipio SET suscripcion = 11402 WHERE territorio = 'Río Ibáñez';
UPDATE D240_municipio SET suscripcion = 12101 WHERE territorio = 'Punta Arenas';
UPDATE D240_municipio SET suscripcion = 12102 WHERE territorio = 'Laguna Blanca';
UPDATE D240_municipio SET suscripcion = 12103 WHERE territorio = 'Río Verde';
UPDATE D240_municipio SET suscripcion = 12104 WHERE territorio = 'San Gregorio';
UPDATE D240_municipio SET suscripcion = 12201 WHERE territorio = 'Cabo de Hornos';
UPDATE D240_municipio SET suscripcion = 12301 WHERE territorio = 'Porvenir';
UPDATE D240_municipio SET suscripcion = 12302 WHERE territorio = 'Primavera';
UPDATE D240_municipio SET suscripcion = 12303 WHERE territorio = 'Timaukel';
UPDATE D240_municipio SET suscripcion = 12401 WHERE territorio = 'Natales';
UPDATE D240_municipio SET suscripcion = 12402 WHERE territorio = 'Torres del Paine';
UPDATE D240_municipio SET suscripcion = 13101 WHERE territorio = 'Santiago';
UPDATE D240_municipio SET suscripcion = 13102 WHERE territorio = 'Cerrillos';
UPDATE D240_municipio SET suscripcion = 13103 WHERE territorio = 'Cerro Navia';
UPDATE D240_municipio SET suscripcion = 13104 WHERE territorio = 'Conchalí';
UPDATE D240_municipio SET suscripcion = 13105 WHERE territorio = 'El Bosque';
UPDATE D240_municipio SET suscripcion = 13106 WHERE territorio = 'Estación Central';
UPDATE D240_municipio SET suscripcion = 13107 WHERE territorio = 'Huechuraba';
UPDATE D240_municipio SET suscripcion = 13108 WHERE territorio = 'Independencia';
UPDATE D240_municipio SET suscripcion = 13109 WHERE territorio = 'La Cisterna';
UPDATE D240_municipio SET suscripcion = 13110 WHERE territorio = 'La Florida';
UPDATE D240_municipio SET suscripcion = 13111 WHERE territorio = 'La Granja';
UPDATE D240_municipio SET suscripcion = 13112 WHERE territorio = 'La Pintana';
UPDATE D240_municipio SET suscripcion = 13113 WHERE territorio = 'La Reina';
UPDATE D240_municipio SET suscripcion = 13114 WHERE territorio = 'Las Condes';
UPDATE D240_municipio SET suscripcion = 13115 WHERE territorio = 'Lo Barnechea';
UPDATE D240_municipio SET suscripcion = 13116 WHERE territorio = 'Lo Espejo';
UPDATE D240_municipio SET suscripcion = 13117 WHERE territorio = 'Lo Prado';
UPDATE D240_municipio SET suscripcion = 13118 WHERE territorio = 'Macul';
UPDATE D240_municipio SET suscripcion = 13119 WHERE territorio = 'Maipú';
UPDATE D240_municipio SET suscripcion = 13120 WHERE territorio = 'Ñuñoa';
UPDATE D240_municipio SET suscripcion = 13121 WHERE territorio = 'Pedro Aguirre Cerda';
UPDATE D240_municipio SET suscripcion = 13122 WHERE territorio = 'Peñalolén';
UPDATE D240_municipio SET suscripcion = 13123 WHERE territorio = 'Providencia';
UPDATE D240_municipio SET suscripcion = 13124 WHERE territorio = 'Pudahuel';
UPDATE D240_municipio SET suscripcion = 13125 WHERE territorio = 'Quilicura';
UPDATE D240_municipio SET suscripcion = 13126 WHERE territorio = 'Quinta Normal';
UPDATE D240_municipio SET suscripcion = 13127 WHERE territorio = 'Recoleta';
UPDATE D240_municipio SET suscripcion = 13128 WHERE territorio = 'Renca';
UPDATE D240_municipio SET suscripcion = 13129 WHERE territorio = 'San Joaquín';
UPDATE D240_municipio SET suscripcion = 13130 WHERE territorio = 'San Miguel';
UPDATE D240_municipio SET suscripcion = 13131 WHERE territorio = 'San Ramón';
UPDATE D240_municipio SET suscripcion = 13132 WHERE territorio = 'Vitacura';
UPDATE D240_municipio SET suscripcion = 13201 WHERE territorio = 'Puente Alto';
UPDATE D240_municipio SET suscripcion = 13202 WHERE territorio = 'Pirque';
UPDATE D240_municipio SET suscripcion = 13203 WHERE territorio = 'San José de Maipo';
UPDATE D240_municipio SET suscripcion = 13301 WHERE territorio = 'Colina';
UPDATE D240_municipio SET suscripcion = 13302 WHERE territorio = 'Lampa';
UPDATE D240_municipio SET suscripcion = 13303 WHERE territorio = 'Tiltil';
UPDATE D240_municipio SET suscripcion = 13401 WHERE territorio = 'San Bernardo';
UPDATE D240_municipio SET suscripcion = 13402 WHERE territorio = 'Buin';
UPDATE D240_municipio SET suscripcion = 13403 WHERE territorio = 'Calera de Tango';
UPDATE D240_municipio SET suscripcion = 13404 WHERE territorio = 'Paine';
UPDATE D240_municipio SET suscripcion = 13501 WHERE territorio = 'Melipilla';
UPDATE D240_municipio SET suscripcion = 13502 WHERE territorio = 'Alhué';
UPDATE D240_municipio SET suscripcion = 13503 WHERE territorio = 'Curacaví';
UPDATE D240_municipio SET suscripcion = 13504 WHERE territorio = 'María Pinto';
UPDATE D240_municipio SET suscripcion = 13505 WHERE territorio = 'San Pedro';
UPDATE D240_municipio SET suscripcion = 13601 WHERE territorio = 'Talagante';
UPDATE D240_municipio SET suscripcion = 13602 WHERE territorio = 'El Monte';
UPDATE D240_municipio SET suscripcion = 13603 WHERE territorio = 'Isla de Maipo';
UPDATE D240_municipio SET suscripcion = 13604 WHERE territorio = 'Padre Hurtado';
UPDATE D240_municipio SET suscripcion = 13605 WHERE territorio = 'Peñaflor';
UPDATE D240_municipio SET suscripcion = 14101 WHERE territorio = 'Valdivia';
UPDATE D240_municipio SET suscripcion = 14102 WHERE territorio = 'Corral';
UPDATE D240_municipio SET suscripcion = 14103 WHERE territorio = 'Lanco';
UPDATE D240_municipio SET suscripcion = 14104 WHERE territorio = 'Los Lagos';
UPDATE D240_municipio SET suscripcion = 14105 WHERE territorio = 'Máfil';
UPDATE D240_municipio SET suscripcion = 14106 WHERE territorio = 'Mariquina';
UPDATE D240_municipio SET suscripcion = 14107 WHERE territorio = 'Paillaco';
UPDATE D240_municipio SET suscripcion = 14108 WHERE territorio = 'Panguipulli';
UPDATE D240_municipio SET suscripcion = 14201 WHERE territorio = 'La Unión';
UPDATE D240_municipio SET suscripcion = 14202 WHERE territorio = 'Futrono';
UPDATE D240_municipio SET suscripcion = 14203 WHERE territorio = 'Lago Ranco';
UPDATE D240_municipio SET suscripcion = 14204 WHERE territorio = 'Río Bueno';
UPDATE D240_municipio SET suscripcion = 15101 WHERE territorio = 'Arica';
UPDATE D240_municipio SET suscripcion = 15102 WHERE territorio = 'Camarones';
UPDATE D240_municipio SET suscripcion = 15201 WHERE territorio = 'Putre';
UPDATE D240_municipio SET suscripcion = 15202 WHERE territorio = 'General Lagos';