//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOX_INFOTMATION
    {
        public long id { get; set; }
        public Nullable<long> id_tema { get; set; }
        public Nullable<long> id_tabla { get; set; }
        public string titulo_box { get; set; }
        public Nullable<long> id_filtro1 { get; set; }
        public string desc_filtro1 { get; set; }
        public Nullable<long> id_filtro2 { get; set; }
        public string desc_filtro2 { get; set; }
        public string descripcion { get; set; }
        public string url_miniatura { get; set; }
        public string url_expandida { get; set; }
        public Nullable<int> activo { get; set; }
        public string aux { get; set; }
        public string aux2 { get; set; }
    }
}
