//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class graficosEntities1 : DbContext
    {
        public graficosEntities1()
            : base("name=graficosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TABLA_GENERICA_PRUEBA> TABLA_GENERICA_PRUEBA { get; set; }
        public virtual DbSet<DATA_METRICA_EDUCACION_160> DATA_METRICA_EDUCACION_160 { get; set; }
        public virtual DbSet<D000_SITIO_PUBLICO> D000_SITIO_PUBLICO { get; set; }
        public virtual DbSet<D100_AGRICULTURA> D100_AGRICULTURA { get; set; }
        public virtual DbSet<D400_INGRESO_HISTORICO> D400_INGRESO_HISTORICO { get; set; }
        public virtual DbSet<D990_AGENCIA_INFORMACION> D990_AGENCIA_INFORMACION { get; set; }
        public virtual DbSet<D360_ENFERMEDADES_MUNDIALES> D360_ENFERMEDADES_MUNDIALES { get; set; }
        public virtual DbSet<D140_ECONOMIA> D140_ECONOMIA { get; set; }
        public virtual DbSet<D300_VIOLENCIA_CONTRA_LA_MUJER> D300_VIOLENCIA_CONTRA_LA_MUJER { get; set; }
        public virtual DbSet<D261_GLACIARES> D261_GLACIARES { get; set; }
        public virtual DbSet<D101_INCENDIOS> D101_INCENDIOS { get; set; }
        public virtual DbSet<PLATAFORMA_AUX> PLATAFORMA_AUX { get; set; }
        public virtual DbSet<CONTENIDO_INSERTADO> CONTENIDO_INSERTADO { get; set; }
        public virtual DbSet<D241_CIUDADES> D241_CIUDADES { get; set; }
        public virtual DbSet<D161_RANKING_COMUNAL_EDUCACION> D161_RANKING_COMUNAL_EDUCACION { get; set; }
        public virtual DbSet<D240_Municipio> D240_Municipio { get; set; }
        public virtual DbSet<MONITOR> MONITOR { get; set; }
        public virtual DbSet<BOX_INFOTMATION> BOX_INFOTMATION { get; set; }
        public virtual DbSet<TABLA_SEMANARIO> TABLA_SEMANARIO { get; set; }
    }
}
