
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Login.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DATA_GRAFICO
{

    public decimal id { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public string titulo { get; set; }

    public string subtitulo { get; set; }

    public string tags { get; set; }

    public string url { get; set; }

    public string iso_pais { get; set; }

    public string nivel_administrativo { get; set; }

    public string descripcion_larga { get; set; }

    public string fecha_publicacion { get; set; }

    public string idioma { get; set; }

    public string responsable { get; set; }

    public string shopify { get; set; }

    public string auxiliar { get; set; }

    public string rango_edad { get; set; }

    public int CATEGORIA_id { get; set; }

    public int PARAMETRO_id { get; set; }

    public int DETALLE_id { get; set; }

    public int TERRITORIO_id { get; set; }

    public int TEMPORALIDAD_id { get; set; }

    public int TIPO_GRAFICO_id { get; set; }

    public int FUENTE_id { get; set; }

    public string unidad_medida { get; set; }

    public string tamanio_muestra { get; set; }

    public string caracteristica_especial { get; set; }

    public string auxiliar_1 { get; set; }

    public int RESPONSABLE_id { get; set; }

    public int UNIDAD_MEDIDA_id { get; set; }



    public virtual CATEGORIA CATEGORIA { get; set; }

    public virtual DETALLE DETALLE { get; set; }

    public virtual FUENTE FUENTE { get; set; }

    public virtual PARAMETRO PARAMETRO { get; set; }

    public virtual RESPONSABLE RESPONSABLE1 { get; set; }

    public virtual TEMPORALIDAD TEMPORALIDAD { get; set; }

    public virtual TERRITORIO TERRITORIO { get; set; }

    public virtual TIPO_GRAFICO TIPO_GRAFICO { get; set; }

    public virtual UNIDAD_MEDIDA UNIDAD_MEDIDA1 { get; set; }

        public string _fecha_publicacion
        {
            get
            {
                string salida = "";
                try
                {
                    if (fecha_publicacion.Contains("/"))
                    {
                        return fecha_publicacion;
                    }
                    DateTime conv = DateTime.FromOADate(Int32.Parse(fecha_publicacion));
                    salida = conv.ToShortDateString();

                }
                catch (Exception)
                {
                    salida = DateTime.Now.ToString("dd/MM/yyyy").Replace("-", "/");
                }
                return salida;
            }

            set { fecha_publicacion = value; }
        }

        public string _titulo
        {
            get
            {
                string salida = "";
                try
                {
                    salida = titulo.Substring(0, 25) + " ...";


                }
                catch (Exception)
                {

                }
                return salida;
            }

            set { _titulo = value; }
        }

        public string _titulo2
        {
            get
            {
                string salida = "";
                try
                {
                    salida = titulo.Substring(0, 53) + " ...";


                }
                catch (Exception)
                {
                    salida = titulo.Substring(0, 20) + " ...";
                }
                return salida;
            }

            set { _titulo2 = value; }
        }

        public int _producto_id
        {
            get
            {
                return this.CATEGORIA.PRODUCTO_id;
            }

            set { _producto_id = value; }
        }

        public string _url_Image
        {
            get
            {
                //string industria_id = CATEGORIA.PRODUCTO.SECTOR.INDUSTRIA_id.ToString("D2");
                //string sector_id = CATEGORIA.PRODUCTO.SECTOR_id.ToString("D2");
                //string producto_id = CATEGORIA.PRODUCTO_id.ToString("D2");
                //string categoria_id = CATEGORIA_id.ToString("D3");
                ////https://raw.githubusercontent.com/Sud-Austral/MPG/main/Datos/001Agricultura/001001Agricultura/0010010001Palta/001001000100001Primera_Palta/paltas3.csv

                //string industria_nombre = CATEGORIA.PRODUCTO.SECTOR.INDUSTRIA.nombre;
                //string sector_nombre = CATEGORIA.PRODUCTO.SECTOR.nombre;
                //string producto_nombre = CATEGORIA.PRODUCTO.nombre;
                //string categoria_nombre = CATEGORIA.nombre;
                //string salida = industria_id + industria_nombre + "/" +
                //            sector_id + sector_nombre + "/" +
                //            producto_id + producto_nombre + "/" +
                //            categoria_id + categoria_nombre + "/";
                //string accentedStr = salida;
                //byte[] tempBytes;
                //tempBytes = System.Text.Encoding.GetEncoding("ISO-8859-8").GetBytes(accentedStr);
                //string asciiStr = System.Text.Encoding.UTF8.GetString(tempBytes);
                //salida = asciiStr.ToLower();
                //salida = "https://github.com/Sud-Austral/MPG/raw/main/Image/" + salida + id.ToString() + ".png";
                /* return salida.Replace(" ", "_");*/
                return "https://raw.githubusercontent.com/Sud-Austral/MPG/main/img/" + id.ToString() + ".png";
            }

            set { fecha_publicacion = "Sin Imagen"; }
        }

        public List<int> suscripciones { get; set; }

        public bool mostrar
        {
            get
            {
                try
                {
                    if (this.TIPO_GRAFICO_id < 3)
                    {
                        return true;
                    }
                    return this.suscripciones.Contains(this.CATEGORIA.PRODUCTO.SECTOR_id);
                }
                catch (Exception)
                {

                    return false;
                }

            }
            set { mostrar = true; }
        }

        public string GetURL()
        {
            string industria_id = CATEGORIA.PRODUCTO.SECTOR.INDUSTRIA_id.ToString("D2");
            string sector_id = CATEGORIA.PRODUCTO.SECTOR_id.ToString("D2");
            string producto_id = CATEGORIA.PRODUCTO_id.ToString("D2");
            string categoria_id = CATEGORIA_id.ToString("D3");
            //https://raw.githubusercontent.com/Sud-Austral/MPG/main/Datos/001Agricultura/001001Agricultura/0010010001Palta/001001000100001Primera_Palta/paltas3.csv

            string industria_nombre = CATEGORIA.PRODUCTO.SECTOR.INDUSTRIA.nombre;
            string sector_nombre = CATEGORIA.PRODUCTO.SECTOR.nombre;
            string producto_nombre = CATEGORIA.PRODUCTO.nombre;
            string categoria_nombre = CATEGORIA.nombre;

            string salida = industria_id + industria_nombre + "/" +
                            sector_id + sector_nombre + "/" +
                            producto_id + producto_nombre + "/" +
                            categoria_id + categoria_nombre + "/" +
                            url;
            string accentedStr = salida;
            byte[] tempBytes;
            tempBytes = System.Text.Encoding.GetEncoding("ISO-8859-8").GetBytes(accentedStr);
            string asciiStr = System.Text.Encoding.UTF8.GetString(tempBytes);
            salida = asciiStr.ToLower();
            return salida.Replace(" ", "_");
        }

    }

}
