using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Login.Models
{
    public class ListaColecciones
    {
        public List<ContenidoColeccion> Generica { get; set; }

        public ListaColecciones()
        {
            Generica = new List<ContenidoColeccion>();
            /************************************Enfermedades Mundiales Pandemia****************************************************************************/
            Generica.Add(new ContenidoColeccion("Asistencia", "/Content/Data Salud Pandemia images/recuadrosweb_DATAsaludPandemias_evolucion_asistencia.png", "Destacan las cifras de evolución de la disponibilidad y utilización de Residencias Sanitarias, el balance de sus cupos y su vista comparativa entre cupos y usuarios. La información se muestra a escala nacional y regional."));
            Generica.Add(new ContenidoColeccion("Diagnóstico", "/Content/Data Salud Pandemia images/recuadrosweb_DATAsaludPandemias_evolucion_diagnostico.png", "Incluye la evolución del número de exámenes PCR por Región, por mes y acumulados y su relación con la positividad, a escala Regional y Nacional."));
            Generica.Add(new ContenidoColeccion("Evolución COVID-19", "/Content/Data Salud Pandemia images/recuadrosweb_DATAsaludPandemias_evolucionCovid19.png", "Específicamente se centra en las cifras de casos activos, casos confirmados y fallecidos. A escala nacional, regional y comunal desde marzo del año 2020 a la fecha."));
            Generica.Add(new ContenidoColeccion("Evolución Vacunación", "/Content/Data Salud Pandemia images/recuadrosweb_DATAsaludPandemias_evolucion_vacunacion.png", "Los gráficos centran su información en la Evolución del proceso de vacunación (1 y 2 dosis) a escala nacional, regional y comunal, según las últimas cifras publicadas."));
            Generica.Add(new ContenidoColeccion("Paso a Paso", "/Content/Data Salud Pandemia images/imagenes_recuadrosweb_pasoapaso.png", "La información monitorea la estrategia gradual sobre la situación sanitaria para las etapas Paso a Paso; vinculando la información entre Paso a Paso y Casos Activos; y Paso a Paso y Vacunación a escala nacional, regional y comunal."));
            /************************************Agencia de información****************************************************************************/
            Generica.Add(new ContenidoColeccion(990, "COVID-19", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_DI_covid.png", "Generamos gráficos con información de los casos activos y fallecidos a nivel nacional, regional y comunal a contar de 2020 a la fecha. El detalle de los gráficos abarca nuevos casos, casos acumulados, recuperados y fallecidos, todos listos para ser difundidos en digital o impreso."));
            Generica.Add(new ContenidoColeccion(990, "Agricultura", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_DI_exportaciones.png", "Recopilamos toda la información de exportaciones de frutas según su tipo de procesamiento, considerando su región de origen y país de destino. Nuestros gráficos interactivos permiten conocer en detalle cifras de volumen, precios diarios, producción y sus evoluciones, todas dispuestas para ser difundidas en formatos virtuales o impresas."));
            Generica.Add(new ContenidoColeccion(990, "Violencia Contra la Mujer", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_violenciacontralamujer.png", "Disponemos la información de violencia contra la mujer segregada por regiones, con sus sentencias, la información de fiscalías y apoyos a la mujer. En nuestros gráficos interactivos también podrás ver la evolución en el tiempo siendo una ayuda vital para conocer a cabalidad el tema, todos disponibles en digital y también para impresión."));
            Generica.Add(new ContenidoColeccion(990, "Mujer Salud", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_DI_cancercuellouterino.png", "Un tema fundamental en Chile es la salud y uno de las prioridades es el cáncer de cuello cervicouterino. En Agencia DI recopilamos la información del periodo 2011-2018,  su evolución de casos, segregados por rango etario, región, y comuna. Todos nuestros gráficos interactivos están disponibles para difusión digital e impresa."));
            Generica.Add(new ContenidoColeccion(990, "Ingresos Históricos", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_DI_IngrresoPromedioMensual.png", "Considerando la realidad social actual del país recopilamos la información de encuestas realizadas en el periodo 2006 a 2017 en materia de caracterización socioeconómica. Considera el Ingreso Promedio Mensual para cada región e incluye los datos también por etnia, tanto en pesos como en porcentajes. Todos nuestros gráficos son interactivos y pueden ser utilizados en formato digital o impreso."));
            Generica.Add(new ContenidoColeccion(990, "Cultura", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_DI_cultura.png", "Conocer la información sobre la infraestructura cultural es fundamental para asegurar la eficacia de los programas culturales comunales. Cultura, de Agencia DI, dispone la información sobre infraestructura, financiamiento, titularidad y acceso a discapacitados de los Centros Culturales ubicadas en las distintas comunas del país."));
            Generica.Add(new ContenidoColeccion(990, "Empresas", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_DI_empresas.png", "La información sobre Empresas de Agencia DI abarca las ventas anuales generadas por rubro y región; la cantidad de trabajadores contratados segregados por género a escala regional y nacional y su diferencia porcentual con respecto al año anterior; el número de empresas según sus ventas en la RM y también según el inicio de actividades y tipo de contribuyente."));
            Generica.Add(new ContenidoColeccion(990, "Métricas de la Educación", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_DI_metricasDelaEducacion.png", "Destacamos la información de la evolución de indicadores tanto de Participación y formación ciudadana como de clima de convivencia en establecimientos por región, la evolución de puntaje SIMCE en lectura y matemáticas y Proporción de Alumnos de con más de 450 puntos en la PSU según dependencia de colegios. Destacamos el uso de mapas para los indicadores de autoestima académica y puntaje promedio SIMCE de lectura por comuna."));
            Generica.Add(new ContenidoColeccion(990, "Inventario de Gases de Efecto Invernadero (GEI)", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_DI_mitigacioncambioclimatico.png", "El uso de fuentes de energía convencionales ha ido en aumento de la mano de las emisiones de CO2. Mitigación del Cambio Climático de Agencia DI dispone la información de los periodos 1990-2018; 1990-2019 y la previsión de 2020-2025 para Chile. La información se encuentra en kilotoneladas (kt) de CO2 eq con el promedio de emisiones netas, emisiones y absorciones por subsector y por región. Además, el mapa de absorciones por región; la emisión por (t) de tipo de combustible, per cápita, variación porcentual y proporción de emisión."));
            Generica.Add(new ContenidoColeccion(990, "Vulnerabilidad", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_DI_vulnerabilidadcambioclimatico.png", "La vulnerabilidad al cambio climático indica el grado al cual un sistema es susceptible de verse afectado de manera adversa por los efectos del cambio climático. Agencia DI dispone la información de las comunas y regiones,  además de su geoposicionamiento."));
            Generica.Add(new ContenidoColeccion(990, "Gestión Municipal Territorial", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_DI_municipio.png", "La información sobre los distintos usos de la superficie en una comuna es fundamental para financiar bienes y servicios comunitarios a través del pago de contribuciones. Agencia DI entrega información de Predios Agrícolas y no Agrícolas, así como la cantidad de plazas, parques y áreas verdes que mantienen las comunas. Datos del periodo 2006 a 2019."));
            Generica.Add(new ContenidoColeccion(990, "Territorio", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_DI_territorio.png", "Territorio, de Agencia DI, mantiene información con el estado de los PRDU vigentes y los IPT activos a nivel regional y comunal. "));
            Generica.Add(new ContenidoColeccion(990, "Tránsito", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_DI_transito.png", "Agencia DI entrega información sobre la evolución del número de licencias y permisos de circulación, según clase de licencia y tipo de vehículo, por comuna, región y a escala nacional. Adicionalmente información de la pasada de vehículos por Pórticos y Plazas de Peajes de autopistas interurbanas ."));
            Generica.Add(new ContenidoColeccion(990, "Energía", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_agenciaDI_energia.png", "Manejar datos sobre la energía generada en el país es fundamental si se quiere tener una visión general del desarrollo económico. En Agencia DI agrupamos información sobre la capacidad instalada (MW) tanto de centrales eléctricas, de centrales de energía renovables y no renovables por región. También la capacidad instalada por tipo de energía y región; un mapa con las centrales de energía renovable no convencional y un ranking de propietarios de centrales eléctricas con mayor capacidad instalada."));
            Generica.Add(new ContenidoColeccion(990, "Elecciones", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_agenciaDI_energia.png", "La valoración de la democracia está en la representación real que esta tenga de la ciudadanía. En Agencia DI presentamos un completo panorama de todos los candidatos electos desde 1990 en adelante, información que entregamos con su lista y partido, más la votación obtenida. Además, complementamos con la cantidad de cupos a cargos de elección popular a escala regional y comunal."));
            Generica.Add(new ContenidoColeccion(990, "Evaluación de Programas", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_agenciaDI_evaluacionprogramas.png", "A la luz de los cambios sociales en Chile es fundamental conocer la calidad del servicio estatal que ha tenido el país a través del tiempo. Una de las formas de establecer una visión de esto es la información existente en la evaluación de programas realizada por cada ministerio que abarca el periodo 1997-2020. Las categorías de evaluación son Ajustes menores, Buen desempeño, Desempeño insuficiente, Rediseño sustantivo, Resultados No demostrados, entre otras."));
            Generica.Add(new ContenidoColeccion(990, "Programas de Salud", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_programasdesalud.png", "En Chile, enfermedades asociadas a la obesidad y el aumento de contagios VIH son los problemas de salud que más preocupan a los investigadores. Teniendo esto en cuenta, Agencia DI recopiló información existente de la evolución de Población en control del Programa VIH/SIDA y la población en control del Programa de Salud Cardiovascular entre los años 2012 y 2018. Cifras según rango etario, por sexo, por enfermedad a nivel regional y comunal."));
            Generica.Add(new ContenidoColeccion(990, "Delincuencia", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_delito.png", "Agencia DI recopiló la información de los delitos de mayor impacto en la comunidad. En Delincuencia damos a conocer el porcentaje de la relación entre detenciones y denuncias de homicidio y violación; un mapa con información de la frecuencia de homicidios; cifras de la variación de frecuencia de robos con violencia o intimidación; y la variación anual de la frecuencia de delitos de mayor connotación social"));
            Generica.Add(new ContenidoColeccion(990, "Demografía", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_estadisticasvitales.png", "En el tema Estadísticas Vitales se plasma la información recopilada de 11 años para la cantidad de defunciones y también la información para la cantidad de nacimientos según la comuna."));
            Generica.Add(new ContenidoColeccion(990, "Forestal", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_forestal.png", "Año a año los incendios forestales se repiten transformando estos hechos fortuitos en una realidad cotidiana. Conocer las causas y la superficie que afectan es fundamental para crear estrategias de prevención. Agencia DI presenta información de cerca de 30 causas por las que se originan estos incendios en un periodo que abarca 10 años de datos."));
            Generica.Add(new ContenidoColeccion(990, "Pueblos indígenas", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/Pueblos indígenas.jpg", "Gráficos interactivos con información de los nueve pueblos indígenas, más la opción “pueblo ignorado” y “otros”. Cantidad de personas autoidentificadas con un pueblo, por rango etario, sexo y según su distribución territorial. Dentro de los pueblos se encuentra el yagán, rapa nui, quechua, mapuche, licán antai, kawésqar, diaguita, colla y aymara."));
            Generica.Add(new ContenidoColeccion(990, "Trabajo", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_trabajo.png", "La fuerza de trabajo considera las personas ocupadas, desocupadas que buscan trabajo por primera vez y cesantes. En los gráficos interactivos se entrega Información actualizada al año 2021, de la variación de la fuerza de trabajo, la tasa de desocupación y variación de los desocupados en Chile, desde el año 1986."));
            Generica.Add(new ContenidoColeccion(990, "Vivienda y Construcción", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_viviendayconstruccion.png", "Información de vivienda y construcción que contiene la evolución de la superficie de edificación habitacional y no habitacional; evolución del número de viviendas autorizadas y la superficie de las solicitudes de edificación por categoría. Todas a escala nacional y mensual."));
            Generica.Add(new ContenidoColeccion(990, "Comercio Exterior", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_comercio.png", "Agencia DI presenta algunas cifras en el tema de Comercio para el año 2021, en cuanto a exportaciones según tipo de producto, producto del mar y valor de exportaciones mineras, según tipo de producto para cada trimestre, año y país. Incluye, mapa de importaciones de alimentos en USD por país de origen y la evolución de importaciones por mes según el producto importado, su volumen en USD."));
            Generica.Add(new ContenidoColeccion(990, "Gestión Municipal de Educación", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_agenciaDI_municipioeducacion.png", "Una clave fundamental para mejorar la calidad de la educación es conocer la cantidad de alumnos en el aula por docente y es una referencia indispensable para estimar el grado de atención ejercido. Agencia DI elaboró un un ranking comunal par el periodo 2019-2020 aplicado a los colegios municipales."));
            Generica.Add(new ContenidoColeccion(990, "Establecimientos de Salud", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_establecimientosalud.png", "El acceso a la salud comienza en la comuna, que la población posea expeditos esos accesos es fundamental. Agencia DI detalla la información de la cantidad de establecimientos de salud, por categorías y farmacias, incluidos mapas y también un ranking con las comunas que mejor satisfacen esa demanda."));
            Generica.Add(new ContenidoColeccion(990, "Estado de la Salud", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_estadodelasalud.png", "En esta época de pandemia y confinamientos la salud mental de las personas se ha visto afectada.  Para establecer qué tanto se ha afectado se hace necesario mirar en retrospectiva. Agencia DI recopiló la información de la evolución de la proporción de las consultas mentales en el periodo previo a la pandemia, entre los años 2009-2017. Incluimos, además de la información a escala nacional, la evolución de la tasa de consultas mentales en ese mismo periodo en escala comunal y regional."));
            Generica.Add(new ContenidoColeccion(990, "Internet", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_internet.png", "¿Qué tan conectados al mundo estamos? Agencia DI estableció un ranking nacional con las comunas con más suscripciones a internet fija prepandemia, entre los años 2007-2019. Incluimos, además,  la cantidad de conexiones en el país actualizadas hasta el año 2019."));
            Generica.Add(new ContenidoColeccion(990, "Minería", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_mineria.png", "Agencia DI recopiló la información generada en los últimos 7 años de tres productos mineros relevantes. Cobre, hierro y cloruro de sodio. Incluimos además,  información con el índice de producción minera en el país en el periodo 2014-2021."));
            Generica.Add(new ContenidoColeccion(990, "Pobreza", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_pobreza.png", "Agencia DI a partir de la información de encuestas realizadas en el periodo 2006 a 2020 en materia de caracterización socioeconómica, genera gráfico de la pobreza y pobreza extrema, incluyendo información de la población autodefinida como indígena, todo a escala comunal, para el año 2020. Además, se agregó la evolución que ha tenido esta situación a escala nacional y regional entre los años 2006 y 2020."));
            Generica.Add(new ContenidoColeccion(990, "Protección de Menores", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_proteccionmenores.png", "Agencia DI presenta información sobre Niños, Niñas y Adolescentes en datos recopilados desde 2016 hasta 2019, proveniente del Servicio Nacional de Menores. Las cifras se disponen en materias de ingresos y egresos a los centros de atención, por línea de atención, su evolución de 3 años y un mapa por región."));
            Generica.Add(new ContenidoColeccion(990, "Transporte", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_transporte.png", "Conozca a través de Agencia DI la evolución que ha tenido el parque vehicular en Chile en el transporte de escolares y en taxis, por región y a nivel nacional entre los años 2014 y 2021."));
            Generica.Add(new ContenidoColeccion(990, "Gestión Municipal de Educación", "/Content/Imagenes agencia_Informacion/Fotos Agencia DI/imagenes_recuadrosweb_agenciaDI_municipioeducacion.png", "Una clave fundamental para mejorar la calidad de la educación es conocer la cantidad de alumnos en el aula por docente y es una referencia indispensable para estimar el grado de atención ejercido. Agencia DI elaboró un un ranking comunal par el periodo 2019-2020 aplicado a los colegios municipales."));
            Generica.Add(new ContenidoColeccion(990, "Turismo", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_economia_turismo.png", "Agencia DI recopiló la información de los últimos 5 años en el tema de Turismo en cuanto a los precios promedios de alojamientos incluyendo la cantidad de pernoctaciones en el periodo 2016-2021."));
            Generica.Add(new ContenidoColeccion(990, "Economía", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_economia.png", "Agencia DI recopiló 7 años de información en el tema de Economía referida a la evolución del índice de Producción Manufacturera (IPMAN),  el índice de producción, la evolución del número de supermercados y la evolución del movimiento de carga portuaria a nivel de regiones y nacional."));
            Generica.Add(new ContenidoColeccion(990, "Pesca y Acuicultura", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_pesca.png", "Agencia Di presenta en el tema de Pesca información sobre la evolución de cosechas acuícolas de distintas especies,  la evolución de desembarque artesanal de algas y la evolución de desembarque industrial a escala nacional."));
            Generica.Add(new ContenidoColeccion(990, "Telecomunicaciones", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_telecomunicaciones.png", "Agencia DI presenta el tema de Telecomunicaciones con la información de la evolución de la cantidad de suscritores de televisión de pago del periodo prepandemia 2017-2019 y las comunas con mayor cantidad de suscriptores del año 2019."));
            Generica.Add(new ContenidoColeccion(990, "Glaciares", "/Content/imagenes glaciares_10/imagenes_recuadrosweb_glaciar_superficiecomplejoglaciar.png", "Dinámica de Cambio de Glaciares son informes interactivos con datos sobre superficie ganada, superficie perdida, superficie con y sin nieve, incluyendo máximas y mínimas para tres Complejos Glaciares de la Región de Los Lagos. La información se encuentra detallada por temporada seca y fría para el período comprendido entre los años 2017 y 2021. Se visualiza en gráficos, mapas interactivos y también en formato pdf."));
            Generica.Add(new ContenidoColeccion(990, "Protección Adultos Mayores", "/Content/Imagenes agencia_Informacion/imagenes_recuadrosweb_adultomayorAgenciaDI.png", "Agencia DI presenta información sobre la población de adultos mayores en Chile, los Establecimientos de Larga Estadía para Adultos Mayores (ELEAM) para el año 2021 y la comparación de los cupos por región y nivel comunal entre los años 2019 y 2021."));

            /************************************Ingreso Historico****************************************************************************/
            Generica.Add(new ContenidoColeccion("Ingreso_Promedio_Mensual", "/Content/Ingresos histodicos imagenes/recuadrosweb_DATASocioeconomico_IngresoPromedioMensual.png", "Destacan las cifras de la evolución de “Ingresos Promedio Mensuales” a nivel Nacional, Regional y Comunal, basado en el análisis de datos obtenidos de las encuestas Caracterización Socioeconómica Nacional (CASEN), y la variación porcentual y en pesos respecto a la encuesta anterior."));
            Generica.Add(new ContenidoColeccion("Ingreso por Etnia", "/Content/Ingresos histodicos imagenes/imagenes_recuadrosweb_ingresos_por_etnia.png", "Destacan las cifras de la evolución de “Ingresos Promedio Mensuales” por Etnia, a nivel Nacional, Regional y Comunal, basado en el análisis de datos obtenidos de las encuestas Caracterización Socioeconómica Nacional (CASEN), y la variación porcentual y en pesos, respecto a la encuesta anterior."));
            Generica.Add(new ContenidoColeccion("Ingreso por Sexo", "/Content/Ingresos histodicos imagenes/recuadrosweb_DATASocioeconomico_IngresoporSexo.png", "Destacan las cifras de la evolución de “Ingresos Promedio Mensuales” de hombres y mujeres, a nivel Nacional, Regional y Comunal, basado en el análisis de datos obtenidos de las encuestas Caracterización Socioeconómica Nacional (CASEN), y la variación porcentual observada para el año 2017."));
            Generica.Add(new ContenidoColeccion("Ingreso por Alfabetismo", "/Content/Ingresos histodicos imagenes/recuadrosweb_DATASocioeconomico_IngresoPorAlfabetismo.png", "Destacan las cifras de la evolución de “Ingresos Promedio Mensuales” entre personas con y sin alfabetización, a nivel Nacional, Regional y Comunal, basado en el análisis de datos obtenidos de las encuestas Caracterización Socioeconómica Nacional (CASEN), y la variación porcentual observada para el año 2017."));
            Generica.Add(new ContenidoColeccion("Ingreso por Sexo y Alfabetismo", "/Content/Ingresos histodicos imagenes/recuadrosweb_DATASocioeconomico_IngresoporSexoYAlfabetismo.png", "Destacan las cifras de la evolución de “Ingresos Promedio Mensuales” y la variación porcentual de éstos, entre mujeres y hombres, con y sin alfabetización, a nivel Nacional, Regional y Comunal, basado en el análisis de datos obtenidos de las encuestas Caracterización Socioeconómica Nacional (CASEN)."));
            Generica.Add(new ContenidoColeccion("Ingreso por Etnia y Alfabetismo", " /Content/Ingresos histodicos imagenes/imagenes_recuadrosweb_ingresos_por_etniayalfabetismo.png", "Destacan las cifras de la evolución de “Ingresos Promedio Mensuales” por Etnia y entre personas con y sin alfabetización, a nivel Nacional, Regional y Comunal, basado en el análisis de datos obtenidos de las encuestas Caracterización Socioeconómica Nacional (CASEN), y la variación porcentual y en pesos, respecto a la encuesta anterior."));
            Generica.Add(new ContenidoColeccion("Ingreso por Etnia y Sexo", " /Content/Ingresos histodicos imagenes/imagenes_recuadrosweb_ingresos_por_etniaysexo.png", "Destacan las cifras de la evolución de “Ingresos Promedio Mensuales” y la variación porcentual de éstos, entre mujeres y hombres pertenecientes a los diferentes pueblos indígenas, a nivel Nacional, Regional y Comunal, basado en el análisis de datos obtenidos de las encuestas Caracterización Socioeconómica Nacional (CASEN)."));
            /************************************Agricultura****************************************************************************/
            Generica.Add(new ContenidoColeccion(100, "Cosecha", "/Content/Data_Usuario agricultura imagenes/recuadrosweb_Agricultura_cosecha.png", "Específicamente se centra en las cifras del volumen de diferentes categorías de cultivos que se producen y cosechan a lo largo de Chile, detallada según cultivo y comuna en la que se produce; en el caso de fruta se detalla también el  procesamiento y tipo de envase que se utiliza para su empaquetamiento."));
            Generica.Add(new ContenidoColeccion(100, "Empresas", "/Content/Data_Usuario agricultura imagenes/recuadrosweb_Agricultura_empresas.png", "Específicamente se centra en la información del número de empresas que existen en el sector agrícola, su distribución a nivel provincial y comunal, detallando el tipo de cultivo con el que trabajan y el procesamiento que realizan de éstos."));
            Generica.Add(new ContenidoColeccion(100, "Empleo", "/Content/Data_Usuario agricultura imagenes/recuadrosweb_Agricultura_empleados.png", "Específicamente se centra en la información del número de empleados catastrados en la actividad frutícola, detallada según género, el tipo de contrato y su distribución a nivel regional."));
            //Generica.Add(new ContenidoColeccion(100, "Producción", "/Content/Data_Usuario agricultura imagenes/recuadrosweb_Agricultura_produccion.png", "Específicamente se centra en las cifras del volumen de diferentes categorías de cultivos que se producen a lo largo de Chile, detallada según cultivo y comuna en la que se produce; en el caso de fruta se detalla también el  procesamiento y tipo de envase que se utiliza para su empaquetamiento."));
            Generica.Add(new ContenidoColeccion(100, "Precios", "/Content/Data_Usuario agricultura imagenes/recuadrosweb_Agricultura_precios.png", "La información entregada responde al monitoreo de los precios de los últimos días de las diferentes frutas y hortalizas comerciadas en los mercados mayoristas del país."));
            Generica.Add(new ContenidoColeccion(100, "Plantaciones", "/Content/Data_Usuario agricultura imagenes/recuadrosweb_Agricultura_plantaciones.png", "Los gráficos muestran información de la superficie de hortalizas, tubérculos y frutales plantadas en Chile, por especie, y su distribución en las diferentes regiones y comunas del país. Para frutales se especifica también superficie según sistema de plantación y riego utilizado."));
            Generica.Add(new ContenidoColeccion(100, "Importaciones", "/Content/Data_Usuario agricultura imagenes/recuadrosweb_Agricultura_importaciones.png", "Destacan las cifras del Volumen  y Valor de las de Importaciones segmentadas por tipo de Cultivo, País de Origen, Procesamiento, Orgánicos y No orgánicos."));
            Generica.Add(new ContenidoColeccion(100, "Exportaciones", "/Content/Data_Usuario agricultura imagenes/recuadrosweb_Agricultura_exportaciones.png", "Destacan las cifras del Volumen  y Valor de las Exportaciones de frutas de Chile, segmentadas por Regiones de Origen, Países de Destino, Tipos de Procesamiento y para cada Fruta específica."));
            Generica.Add(new ContenidoColeccion(100, "Rendimiento", "/Content/Data_Usuario agricultura imagenes/recuadrosweb_Agricultura_rendimiento.png", "Los gráficos destacan la información de los quintales por hectáreas obtenidos según tipo de cultivo y la variación en el rendimiento en las diferentes regiones de Chile."));
            Generica.Add(new ContenidoColeccion(100, "Ventas Estimadas", "/Content/Data_Usuario agricultura imagenes/imagene_recuadrosweb_Coleccion_agricultura_ventas.png", "Se centra en las cifras de ventas estimadas de la industria agrícola. La información se detalla para cada tipo de cultivo y según los diferentes tamaños de empresa existentes a nivel Nacional, Regional y Comunal. La fuente base de los datos comprende los años 2000 y 2020 según lo publicado por el Servicio de Impuestos internos de Chile (SII)."));
            /************************************ECONOMIA****************************************************************************/
            Generica.Add(new ContenidoColeccion("Comercio", "/Content/imagenes_temas economia/imagenes_recuadrosweb_economia_comercio.png", "En el tema de Supermercados exhibimos la evolución de la actividad midiéndolos a través del Índice de Ventas de Supermercados (ISUP) a escala Nacional y Regional. Todas la información está basada en datos publicados por el Instituto Nacional de Estadísticas (INE)."));
            Generica.Add(new ContenidoColeccion("Construcción", "/Content/imagenes_temas economia/imagenes_recuadrosweb_economia_construccion.png", "En el rubro de Construcción generamos gráficos sobre la evolución de la Superficie de solicitudes de edificación Habitacional y No Habitacional autorizadas, Obras Nuevas o Ampliación. Incorporamos gráficos relacionados con la Evolución Mensual del Número de  Viviendas autorizadas para Construcción. Toda esta información se presenta a escala Nacional y Regional para el periodo 2014-2021."));
            Generica.Add(new ContenidoColeccion("Electricidad", "/Content/imagenes_temas economia/imagenes_recuadrosweb_economia_electricidad.png", "En el tema de Electricidad presentamos información sobre la evolución de la producción de electricidad de las distintas centrales generadoras reportadas y la distribución según sector. Toda la información es a escala Nacional para el periodo 2014-2021. "));
            Generica.Add(new ContenidoColeccion("Manufacturas", "/Content/imagenes_temas economia/imagenes_recuadrosweb_economia_manufactura.png", "Destacan las cifras de la evolución del Índice de Producción Manufacturera (IPMan) y las cifras de producción de queso, quesillo, mantequilla, yodo y molienda de trigo. Toda la información es a escala Nacional para el periodo 2014-2021. "));
            Generica.Add(new ContenidoColeccion("Minería", "/Content/imagenes_temas economia/imagenes_recuadrosweb_economia_mineria.png", "En Minería la información se centra en la evolución del Índice de Producción Minera (IPMin) de las empresas dedicadas a esta actividad. Se entregan las cifras de la producción de minerales metálicos y no metálico según datos registrados por región. Toda la información es a escala Nacional y Regional para el periodo 2014-2021. "));
            Generica.Add(new ContenidoColeccion("Pesca", "/Content/imagenes_temas economia/imagenes_recuadrosweb_economia_pesca.png", "Pesca centra su información en las cifras de evolución de las Cosechas Acuícola y el desembarque tanto Industrial como Artesanal.  Los datos se encuentran organizados a escala nacional y diferenciado por tipo de producto entre los años 2014 y 2021. "));
            Generica.Add(new ContenidoColeccion("Silvoagropecuario", "/Content/imagenes_temas economia/imagenes_recuadrosweb_economia_silvoagropecuario.png", "Silvoagropecuario compendia la información de 3 productos del sector: Leche, Uva y Madera. Específicamente se muestra la evolución de Producción de Uva, Leche Recepcionada y la Cosecha de trozas a nivel nacional para el periodo comprendido entre los años 2014 y 2021."));
            Generica.Add(new ContenidoColeccion("Transporte", "/Content/imagenes_temas economia/imagenes_recuadrosweb_economia_transporte.png", "Incluye la evolución del Parque Vehicular  de Taxis, Buses, Minibuses y transporte Escolar a nivel Nacional y Regional. Adicionalmente, las cifras Nacionales y para las regiones de Valparaíso, Biobío, Metropolitana y Ñuble de las pasadas por Pórticos y Plazas de Peaje de las autopistas interurbanas, para el periodo comprendido entre los años 2014 y 2021. "));
            Generica.Add(new ContenidoColeccion("Transporte Carga", "/Content/imagenes_temas economia/imagenes_recuadrosweb_economia_transportecargamaritima.png", "Los gráficos centran su información en la Evolución del Movimiento de Carga Portuaria a nivel Nacional y en las regiones de Tarapacá, Valparaíso y Biobío. También abarca la evolución del número de contenedores manipulados en puerto según cifras registradas para el periodo 2014-2021."));
            Generica.Add(new ContenidoColeccion("Turismo", "/Content/imagenes_temas economia/imagenes_recuadrosweb_economia_turismo.png", "La información de Turismo destaca la evolución y previsión de variables relacionadas con el Precio Promedio por Habitación (ADR), el Rendimiento del ingreso por habitación disponible (RevPAR) y el Número total de noches de estadía para el periodo 2014-2021, a escala Nacional y Regional. "));
            /************************************VIOLENCIA CONTRA LA MUJER****************************************************************************/
            Generica.Add(new ContenidoColeccion("Femicidios", "/Content/imagenes_Violencia/recuadrosweb_ViolenciaContraLaMujer_femicidios2.png", "Destacan las cifras de Femicidios ocurridos entre los años 2010 y 2021, la evolución y frecuencia detallados por año, a nivel de región y comuna y los casos según edad y la relación existente entre víctima y femicida."));
            Generica.Add(new ContenidoColeccion("Violación", "/Content/imagenes_Violencia/recuadrosweb_ViolenciaContraLaMujer_violaciones.png", "Los Gráficos Interactivos de Violaciones contienen información respecto a la evolución, de las Casos Policiales, Aprehensiones, Denuncias y Detenciones, vinculadas a delitos de Violación, durante el periodo comprendido entre los años 2008 y 2020. Adicionalmente entregamos información de los procesos de Sentencias dictadas por Delitos contra la Mujer, ocurridas entre los años 2013 y 2019."));
            Generica.Add(new ContenidoColeccion("Abuso Sexual", "/Content/imagenes_Violencia/recuadrosweb_ViolenciaContraLaMujer_abusosexual.png", "Los Gráficos Interactivos de Abuso Sexual entregan información del número de Sentencias por Delito, por el Juzgado de garantía que dictó la sentencia  y a nivel regional,  transcurridos entre los años 2013 y 2019."));
            Generica.Add(new ContenidoColeccion("Violencia Intrafamiliar", "/Content/imagenes_Violencia/recuadrosweb_ViolenciaContraLaMujer_violenciaintrafamiliar.png", "Los Gráficos Interactivos de Violencia Intrafamiliar, muestran la frecuencia de Denuncias, Aprehensiones, Detenciones y Casos Policiales, en el periodo 2005 y 2021, según el Centro de Estudio y Análisis del Delito (CEAD). Adicionalmente entregan información de los casos registrados en la Fiscalía en el período 2019-2021."));
            Generica.Add(new ContenidoColeccion("Sentencias por delitos vinculados a la mujer", "/Content/imagenes_Violencia/recuadrosweb_ViolenciaContraLaMujer_sentenciaspordelitosvinculadosalamujer.png", "Cifras vinculadas a las Sentencias por Delitos vinculados a la Mujer entregan información del número de sentencias, por tipo de Delito, por Delito y por el Juzgado de garantía que dictó la sentencia,  transcurridos entre los años 2013 y 2019, a nivel nacional y  regional."));
            Generica.Add(new ContenidoColeccion("Violencia Económica", "/Content/imagenes_Violencia/recuadrosweb_ViolenciaContraLaMujer_violenciaeconomica.png", "Nuestros Gráficos Interactivos de Violencia Económica, muestra las cifras relevantes obtenidas de la Encuesta de Violencia contra la Mujer en el Ámbito de Violencia Intrafamiliar y en Otros Espacios (ENVIF-VCM) realizada por la Subsecretaría de Prevención del Delito de Chile, en los años 2012, 2017 y 2020."));
            Generica.Add(new ContenidoColeccion("Centros de Apoyo", "/Content/imagenes_Violencia/recuadrosweb_ViolenciaContraLaMujer_centrosdeapoyoalamujer.png", "Cifras relevantes de la cantidad  de mujeres atendidas en Centros de Apoyo, Centros de la Mujer, Centros de Atención y Reparación para Mujeres Víctimas/Sobrevivientes de Violencia Sexual (CVS), Casas de Acogida y cantidad de hombres atendidos en Centros de Reeducación de Hombres."));
            Generica.Add(new ContenidoColeccion("Acoso Callejero", "/Content/imagenes_Violencia/recuadrosweb_ViolenciaContraLaMujer_acosocallejeero.png", "Detalle de las cifras obtenidas para cada una de las 7 preguntas incluidas en la encuesta aplicada a hombres y mujeres de Chile de acuerdo a los datos publicados por el INJUV."));
            Generica.Add(new ContenidoColeccion("Atenciones de Salud por Violencia de Género", " /Content/imagenes_Violencia/recuadrosweb_ViolenciaContraLaMujer_atencionsaludviolenciagenero.png", "Destacan las cifras de casos  de Atenciones Salud por Violencia de Genero, información de la evolución histórica de los casos atendidos en los diferentes conceptos de atención consideradas como Violencia de Género, detallados por Región y por servicio Nacional de Salud, para el periodo comprendido entre los años 2010 y 2016."));
            /************************************Glaciares****************************************************************************/
            Generica.Add(new ContenidoColeccion("Dinámica de Cambio de Glaciares en Época de MAYOR acumulación q2 (May-Dic)", "/Content/imagenes glaciares_10/imagenes_recuadrosweb_glaciar_dinamicatemporadafria.png", "Los gráficos de Dinámica de Cambio de Glaciares en temporada Fría muestran la superficie en hectáreas ganadas, las pérdidas, situaciones sin nieve y sin cambio, en la época en la que se produce una mayor acumulación potencial de nieve entre los meses de mayo a diciembre para los diferentes Complejos Glaciares existentes en la región de Los Lagos."));
            Generica.Add(new ContenidoColeccion("Dinámica de Cambio de Glaciares en Época de MENOR acumulación q1 (Ene-Abr)", "/Content/imagenes glaciares_10/imagenes_recuadrosweb_glaciar_superficiecomplejoglaciar.png", "Los gráficos de Dinámica de Cambio de Glaciares en temporada Seca muestran la superficie en hectáreas ganadas, las pérdidas, situaciones sin nieve y sin cambio, en la época en la que se produce una menor acumulación potencial de nieve, entre los meses de enero y abril, para los diferentes Complejos Glaciares existentes en la región de Los Lagos."));
            Generica.Add(new ContenidoColeccion("Superficie de Glaciares en Época de MAYOR acumulación q2 (May-Dic)", "/Content/imagenes glaciares_10/imagenes_recuadrosweb_glaciar_superficietemporadaseca.png", "Detalle de la superficie máximas y mínimas de nieve y la superficie con y sin nieve para los diferentes Complejos Glaciares existentes en la región de Los Lagos, durante la temporada Fría del periodo comprendido entre los años 2017 y 2021. "));
            Generica.Add(new ContenidoColeccion("Superficie de Glaciares en Época de MENOR acumulación q1 (Ene-Abr)", " /Content/imagenes glaciares_10/imagenes_recuadrosweb_glaciar_superficietemporadafria.png", "Detalle de la superficie máxima y mínima de nieve y la superficie con y sin nieve para los diferentes Complejos Glaciares existentes en la región de Los Lagos, durante la temporada Seca del periodo comprendido entre los años 2017 y 2021. "));
            Generica.Add(new ContenidoColeccion("Superficie del Complejo Glaciar", " /Content/imagenes glaciares_10/imagenes_recuadrosweb_glaciar_dinamicatemporadaseca.png", "Destaca la superficie total de cada uno de los complejos Glaciares, es decir, la suma de cada uno de los polígonos que conforman cada complejo glaciar. Información georreferenciada por polígono y especificaciones del sector, comuna, sub subcuenca, entre otros datos relacionados. "));
            /************************************Incendios****************************************************************************/
            Generica.Add(new ContenidoColeccion("Daño - Plantaciones", " /Content/Suscripcion Incendios imagenes/imagen_recuadrosweb_incendios_Dano.png", "Daño en Plantaciones reúne información estadística de la superficie de plantaciones forestales afectadas por incendios, su evolución y variación entre temporadas, además de la ubicación de cada suceso según año y mes de ocurrencia para el periodo 2010-2021. Toda la información se encuentra a nivel nacional, regional y comunal."));
            Generica.Add(new ContenidoColeccion("Superficie por Incendio", "/Content/Suscripcion Incendios imagenes/imagen_recuadrosweb_incendios_DanoEnPlantaciones.png", "En el tema Superficie por Incendio destacan las cifras de superficie promedio afectada por incendio, su evolución y variación por temporada. Mediante gráficos y mapas interactivos se entrega información adicional de las causas generales y específicas, de la temporalidad y ubicación de cada suceso para el periodo 2010-2021. Toda la información se encuentra a nivel nacional, regional y comunal."));
            Generica.Add(new ContenidoColeccion("Ocurrencia - Otros Usos", "/Content/Suscripcion Incendios imagenes/imagen_recuadrosweb_incendios_DanoEnVegetacionNatural.png", "Ocurrencia en Otros Usos de Suelo reúne información estadística del número de incendios en otros usos de suelo, su evolución y variación entre temporadas para el periodo 2010-2021. Toda la información se encuentra a nivel nacional, regional y comunal."));
            Generica.Add(new ContenidoColeccion("Daño", " /Content/Suscripcion Incendios imagenes/imagenes_recuadrosweb_incendios_DanoEnOtrosUsosDeSuelo.png", "En el tema de Daño destacan las cifras de la superficie afectada por incendios forestales junto con su evolución y variación por temporada. Mediante gráficos y mapas interactivos se entrega información adicional de las causas generales y específicas, de la temporalidad y ubicación de cada suceso durante el periodo 2010-2021. Toda la información se encuentra a nivel nacional, regional y comunal."));
            Generica.Add(new ContenidoColeccion("Ocurrencia", " /Content/Suscripcion Incendios imagenes/imagenes_recuadrosweb_incendios_Ocurrencia.png", "En el tema de Ocurrencia destacan las cifras del número de incendios forestales, su evolución y variación por temporada. Mediante gráficos y mapas interactivos se entrega información adicional de las causas generales y especificas, de la temporalidad y ubicación de cada suceso para el periodo 2010-2021. Toda la información se encuentra a nivel nacional, regional y comunal. "));
            Generica.Add(new ContenidoColeccion("Ocurrencia - Vegetación Natural", "/Content/Suscripcion Incendios imagenes/imagenes_recuadrosweb_incendios_OcurrenciaEnPlantaciones.png", "Ocurrencia en Vegetación Natural reúne información estadística del número de incendios en vegetación natural, su evolución y variación entre temporadas para el periodo 2010-2021. Toda la información se encuentra a nivel nacional, regional y comunal."));
            Generica.Add(new ContenidoColeccion("Ocurrencia - Plantaciones", "/Content/Suscripcion Incendios imagenes/imagenes_recuadrosweb_incendios_OcurrenciaEnVegetacionNatural.png", "Ocurrencia en Plantaciones reúne información estadística del número de incendios en plantaciones forestales, su evolución y variación entre temporadas para el periodo 2010-2021. Toda la información se encuentra a nivel nacional, regional y comunal."));
            Generica.Add(new ContenidoColeccion("Daño - Vegetación Natural", "/Content/Suscripcion Incendios imagenes/imagenes_recuadrosweb_incendios_OcurrenciaEnOtrosUsosDeSuelo.png ", "Daño en Vegetación Natural reúne información estadística de la superficie de vegetación natural afectadas por incendios, su evolución y variación entre temporadas, además de la ubicación de cada suceso según año y mes de ocurrencia para el periodo 2010 - 2021. Toda la información se encuentra a nivel nacional, regional y comunal. "));
            Generica.Add(new ContenidoColeccion("Superficie por Incendio - Otros Usos", "/Content/Suscripcion Incendios imagenes/imagenes_recuadrosweb_incendios_SuperficiePorIncendio.png ", "Superficie por Incendio en Otros Usos de Suelo reúne información estadística de la superficie por incendio de otros usos de suelo afectadas y de su evolución y variación entre temporadas para el periodo 2010-2021. Toda la información se encuentra a nivel nacional, regional y comunal."));
            Generica.Add(new ContenidoColeccion("Daño - Otros Usos", "/Content/Suscripcion Incendios imagenes/imagenes_recuadrosweb_incendios_SuperficiePorIncendioEnPlantaciones.png ", "Daño en Otros Usos de Suelo reúne información estadística de la superficie afectada por incendios, su evolución y variación entre temporadas, además de la ubicación de cada suceso según año y mes de ocurrencia para el periodo 2010-2021. Toda la información se encuentra a nivel nacional, regional y comunal. "));
            Generica.Add(new ContenidoColeccion("Superficie por Incendio - Plantaciones", "/Content/Suscripcion Incendios imagenes/imagenes_recuadrosweb_incendios_SuperficiePorIncendioEnVegetacionNatural.png ", "Superficie por Incendio en Plantaciones reúne información estadística de la superficie por incendio de plantaciones forestales afectadas y de su evolución y variación entre temporadas para el periodo 2010-2021. Toda la información se encuentra a nivel nacional, regional y comunal. "));
            Generica.Add(new ContenidoColeccion("Superficie por Incendio - Vegetación Natural", "/Content/Suscripcion Incendios imagenes/imagenes_recuadrosweb_incendios_SuperficiePorIncendioEnOtrosusosDeSuelo.png", "Superficie por Incendio en Vegetación Natural reúne información estadística de la superficie por incendio de vegetación natural afectada y de su evolución y variación entre temporadas para el periodo 2010-2021. Toda la información se encuentra a nivel nacional, regional y comunal."));

            /************************************Municipio****************************************************************************/

            Generica.Add(new ContenidoColeccion(240, "Contexto Sociodemográfico", "/Content/imgenes coleccion municipio/imagenesColeccionMunicipio_Sociodemograficos.png", "Caracterización de la población comunal a través de gráfico y mapas interactivos que detallan información respecto al número de habitantes por sexo, rango etario, pertenencia algún pueblo indígena o procedencia de otro país. Caracterización de la población comunal según las características de la vivienda que habitan y según la situación laboral y escolar, según cifras del Censo 2017.  Proyección de la Población al año 2035. Toda la información es entregada a escala de Zona o distrito de la comuna consultada."));
            Generica.Add(new ContenidoColeccion(240, "Estadísticas Vitales", "/Content/imgenes coleccion municipio/imagenesColeccionMunicipio_Estadisticas.png", "En el tema Estadísticas Vitales se plasma la información recopilada de 11 años para la cantidad de defunciones y de nacimientos y la evolución de la población general según edad, sexo y zona según la comuna, en base a la información obtenida del Ministerio de Salud y el Instituto Nacional de Estadísticas."));
            Generica.Add(new ContenidoColeccion(240, "Pueblos Indígenas", "/Content/imgenes coleccion municipio/imagenesColeccionMunicipio_PoblacionIndigena.png", "Gráficos y mapas interactivos con información de cantidad y proporción de personas autoidentificadas con un pueblo, por etnia, sexo y rango etario, según cifras del Censo 2017. Información de la evolución de ingreso promedio, pobreza y pobreza extrema por Etnia, Sexo y Alfabetismo, basado en el análisis de datos obtenidos de las encuestas Caracterización Socioeconómica Nacional (CASEN), de los años 2006/2009/2011/2013/2015/2017/2020.  "));
            Generica.Add(new ContenidoColeccion(240, "Salud", "/Content/imgenes coleccion municipio/imagenesColeccionMunicipio_Salud.png", "La salud de la población es abordada, a nivel comunal, por medios de programas que permiten un seguimiento integrado del paciente. Esto genera información de la evolución del número de personas en control para los programas de Salud Cardiovascular, VIH y Cáncer de Cuello Uterino. Todos los datos se encuentran segregados por rango etario y servicio nacional de salud. Adicionalmente, se incorporó información sobre los establecimientos de salud públicos y privados existentes en la comuna."));
            Generica.Add(new ContenidoColeccion(240, "Espacios Culturales", " /Content/imgenes coleccion municipio/imagenesColeccionMunicipio_Cultura.png", "La información sobre la infraestructura cultural es fundamental para asegurar la eficacia de los programas culturales comunales. Cultura, dispone esta información de la infraestructura, titularidad y el acceso a discapacitados de los Espacios Culturales en las comunas del país"));
            Generica.Add(new ContenidoColeccion(240, "Telecomunicaciones", " /Content/imgenes coleccion municipio/imagenesColeccionMunicipio_Telecomunicaciones.png", "¿Qué tan conectados al mundo estamos? En temas de Telecomunicaciones e Internet graficamos la evolución de las suscripciones a internet fija y Tv de pago prepandemia, entre los años 2007 - 2019."));
            Generica.Add(new ContenidoColeccion(240, "Violencia contra la Mujer", " /Content/imgenes coleccion municipio/imagenesColeccionMunicipio_Violencia.png", "Violencia contra la Mujer agrupa gráficos interactivos con información estadística de denuncias por Violación entre los años 2008 y 2020; incluye Aprehensiones, Casos Policiales, Denuncias y Detenciones por Violencia Intrafamiliar ocurridos en el periodo 2005 y 2021; se detalla la Evolución de Femicidios en los últimos 10 años junto con la Violencia Económica ejercida. Anexamos los datos de la Encuesta de Violencia contra la Mujer en el Ámbito de Violencia Intrafamiliar y en Otros Espacios (ENVIF-VCM) realizada en los años 2012, 2017 y 2020. "));
            Generica.Add(new ContenidoColeccion(240, "Tránsito", " /Content/imgenes coleccion municipio/imagenesColeccionMunicipio_Transito.png", "Tránsito, entrega información sobre la evolución del número de licencias de conducir por clase de licencia y permisos de circulación por tipo de transporte y tipo de vehículo en la comuna. "));
            Generica.Add(new ContenidoColeccion(240, "Incendios", "/Content/imgenes coleccion municipio/imagenesColeccionMunicipio_Incendios.png", "Año a año los incendios forestales se repiten transformando estos hechos fortuitos en una realidad cotidiana. Conocer las causas y la superficie que afectan es fundamental para crear estrategias de prevención incluso a nivel comunal. Incendios, presenta información de ocurrencia y daños, según causas generales y específicas por las que se originan estos incendios, para las temporadas 2010-2011 al 2020-2021"));
            Generica.Add(new ContenidoColeccion(240, "Energía", " /Images/imagen_recuadrosweb_MUNICIOPIO_Energia.png", "Información del número de Centrales Eléctricas en Operación, según Capacidad Instalada, Generación Distribuida y Potencia Bruta, detallado  por tipo de energía:  Convencional y Energía Renovable No Convencional (ERNC), y especificada para cada central. Información del Precio promedio del día, semana, mes y año de del Kerosene y  los combustibles Gasolina (93, 95 y 97), Gas Natural Comprimido (GNC), Licuado de Petróleo (GLP) y Petróleo. Evolución del precio según empresa y distribuidor y Mapa de las estaciones de combustible según rango fluctuante desde el más alto y más bajo precio. "));
            Generica.Add(new ContenidoColeccion(240, "Empresas", " /Content/imgenes coleccion municipio/imagenesColeccionMunicipio_Empresas.png", "La información sobre Empresas abarca las ventas anuales generadas por rubro, la cantidad de trabajadores contratados segregados por género y su diferencia porcentual con respecto al año anterior y el número de empresas según sus ventas e inicio de actividades y tipo de contribuyente. Incluye datos existentes desde el año 1992 al 2019."));
            Generica.Add(new ContenidoColeccion(240, "Delincuencia", " /Content/imgenes coleccion municipio/imagenesColeccionMunicipio_Delincuencia.png", "Delincuencia muestra información de la relación entre detenciones y denuncias de homicidio y violación, y cifras de la variación de frecuencia de homicidios y de robos con violencia o intimidación a nivel comunal."));
            Generica.Add(new ContenidoColeccion(240, "Caracterización Biofísica", " /Content/imgenes coleccion municipio/imagenesColeccionMunicipio_DatosBiofisicos.png", "Datos Biofísicos de la comuna, contiene gráficos y mapas interactivos de las variables de temperatura y precipitación con diferentes variantes, y la caracterización del suelo según sus variables químicas y físicas detalladas a diferentes profundidades, para el año 2021."));
            Generica.Add(new ContenidoColeccion(240, "Gestión Municipal", " /Content/imgenes coleccion municipio/imagenesColeccionMunicipio_GestionMunicipalSalud.png", "En Gestión Municipal Salud se muestra información de la cobertura de salud municipal en la cantidad de consultas por morbilidad a mayores de 65 años, atención primaria y personas inscritas en FONASA; incluye el número de establecimientos de la Red Asistencial de Salud Municipal y el detalle del personal de Salud. Adicionalmente, se muestra el presupuesto Municipal destinado a salud, Ingresos y Gastos, y la relación existente con las variables de cobertura, establecimientos y personal de la salud. Datos recopilados desde el año 2001 al 2020 según variable. "));
            Generica.Add(new ContenidoColeccion(240, "Educación", " /Content/imgenes coleccion municipio/imagenesColeccionMunicipio_GestionMunicipal.png", "En Gestión Municipal Educación se muestra información de la cobertura de educación municipal. Incluye información estadísticas de personas en edad escolar, cantidad de alumnos matriculados por nivel, asistencia y proporción de alumnos retirados, cantidad de alumnos con más de 450 puntos en la PSU, personal docente y número de establecimientos. Adicionalmente, incorporamos el presupuesto Municipal destinado a educación, Ingresos y Gastos, y la relación existente con las variables de cobertura, docentes y alumnos con más de 450 puntos en la PSU. Datos recopilados desde el año 2001 al 2020."));
            Generica.Add(new ContenidoColeccion(240, "Gestión Comunitaria y Social", " /Content/imgenes coleccion municipio/imagenesColeccionMunicipio_GestionComunitariay.png", "Gestión Comunitaria y Social entrega información respecto a los recursos gestionados por el municipio en materia de educación; pensiones y subsidios; oportunidades de capacitaciones y empleos; recursos para la prevención de delitos; y establecimientos municipales. Según disponibilidad de datos en el Sistema Nacional de Información Municipal (SINIM) entre los años 2001 y 2020."));
            Generica.Add(new ContenidoColeccion(240, "Administración y Finanzas", " /Content/imgenes coleccion municipio/imagenColeccionMunicipio_Administraciony.png", "Administración y Finanzas reúne gráficos relativos a la gestión del presupuesto del Municipio:  evolución y detalle de los ingresos y egresos por área de gestión o sector, según datos disponibles en el Sistema Nacional de Información Municipal (SINIM) para los años 2001 – 2020."));
            Generica.Add(new ContenidoColeccion(240, "Recursos Humanos para la Gestión Municipal", " /Content/imgenes coleccion municipio/imagenesColeccionMunicipio_RecursosHumanos.png", "Recursos humanos reúne gráficos relativos al personal para la gestión eficiente del Municipio; detalla la cantidad de funcionarios según si son o no profesionales, si están a contrata u honorarios, por escalafón directivo o profesional, si están destinados a programas comunitarios o al sector municipal, diferenciados por sexo. Datos procesados y sistematizados, según disponibilidad en el Sistema Nacional de Información Municipal (SINIM) entre los años 2001–2020."));
            /*sección agregado a municipio de ciudades*/
            Generica.Add(new ContenidoColeccion(240, "Distancia a Servicios", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_MapasInteractivosDistanciasServicios.png", "Mapas Interactivos de distancias a servicios reúne una serie mapas interactivos y mapas descargables en formato pdf que detalla la distancia de diferentes localidades o zonas de la comuna, a los diferentes establecimientos de utilidad para las personas: Centros de Salud; Carabineros; Establecimientos de Educación Parvularia, Básica y Media; Sitios de Interés Turístico; Monumentos Nacionales y otros sitios de interés de la población. Toda la información se encuentra geolocalizada a nivel de Zona y Manzana."));
            Generica.Add(new ContenidoColeccion(240, "Establecimientos", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_DistanciasServicios.png", "Gráficos interactivos con el resumen de Información relativa a cantidad de habitantes, de mujeres, de niños y de mayores de 65 años, distribuidos según rango de distancia a centros de Salud, Carabineros, establecimientos de Educación Parvularia, Educación Básica y Media y Educación Superior, Monumentos Nacionales, Sitios de Interés Turístico y Poblacional. Esta misma información se entrega considerando la cantidad de Hogares y viviendas. La información es obtenida con base en análisis de imágenes satelitales e información del Censo para los centros urbanos, pueblos y localidades de la comuna."));
            Generica.Add(new ContenidoColeccion(240, "Viviendas", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_Viviendas.png", "Gráficos interactivos con Información relativa a la cantidad de Viviendas distribuidas según el rango de distancia a los diferentes establecimientos de utilidad: Centros de Salud; Carabineros; Establecimientos de Educación Parvularia, Básica y Media; Sitios de Interés Turístico, Monumentos Nacionales y otros sitios de interés de la población. Adicionalmente se detalla la cantidad de viviendas según el rango de los Índices Espectrales de Temperatura, Índices de Suelo Desnudo (BSI), Índices de Vegetación (NDVI), Índices de Vegetación Ajustado al Suelo (SAVI) e Índice de Vegetación Enriquecido (EVI). La información es obtenida con base en análisis de imágenes satelitales e información del Censo para los centros urbanos, pueblos y localidades de la comuna."));
            Generica.Add(new ContenidoColeccion(240, "Hogares", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_Hogares.png", "Gráficos interactivos con Información relativa a la cantidad de Hogares distribuidos según el rango de distancia a los diferentes establecimientos de utilidad: Centros de Salud; Carabineros; Establecimientos de Educación Parvularia, Básica y Media; Sitios de Interés Turístico, Monumentos Nacionales y otros sitios de interés de la población. Adicionalmente se detalla la cantidad de hogares según el rango de los Índices Espectrales de Temperatura, Índices de Suelo Desnudo (BSI), Índices de Vegetación (NDVI), Índices de Vegetación Ajustado al Suelo (SAVI) e Índice de Vegetación Enriquecido (EVI). La información es obtenida con base en análisis de imágenes satelitales e información del Censo para los centros urbanos, pueblos y localidades de la comuna."));
            Generica.Add(new ContenidoColeccion(240, "Distribución de Niños", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_Ninos.png", "Gráficos interactivos con Información relativa a la cantidad de niños entre los 0-5 años y 6-14 años, distribuidas según el rango de distancia a los diferentes establecimientos de utilidad: Centros de Salud; Establecimientos de Educación Parvularia, Básica, Media y Superior. La información es obtenida con base en análisis de imágenes satelitales e información del Censo para los centros urbanos, pueblos y localidades de la comuna."));
            Generica.Add(new ContenidoColeccion(240, "Distribución de Población", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_Poblacion.png", "Gráficos interactivos con Información relativa a la cantidad de personas, distribuidas según el rango de distancia a los diferentes establecimientos de utilidad: Centros de Salud; Carabineros; Establecimientos de Educación Parvularia, Básica y Media; Sitios de Interés Turístico; Monumentos Nacionales y otros sitios de interés de la población. Adicionalmente se detalla la cantidad de personas según el rango de los Índices Espectrales de Temperatura, Índices de Suelo Desnudo (BSI), Índices de Vegetación (NDVI), Índices de Vegetación Ajustado al Suelo (SAVI) e Índice de Vegetación Enriquecido (EVI). La información es obtenida con base en análisis de imágenes satelitales e información del Censo para los centros urbanos, pueblos y localidades de la comuna."));
            Generica.Add(new ContenidoColeccion(240, "Índices Espectrales", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_IndicesEspectrales.png", "Índices Espectrales, reúne una serie mapas interactivos, mapas descargables y gráficos que detallan información relativa a los Índices de Vegetación (NDVI), Índices de Vegetación Ajustado al Suelo (SAVI) e Índice de Vegetación Enriquecido (EVI); Índices de Suelo Desnudo (BSI) y Temperatura de diferentes centros urbanos de la comuna, relacionado también con la cantidad de población, mujeres, adultos mayores, niños, viviendas y hogares contabilizados en estos centros. Toda la información se encuentra geolocalizada a nivel de Zona y Manzana."));
            Generica.Add(new ContenidoColeccion(240, "Número de Mujeres por Distancia a Servicios", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_Mujeres.png", "Gráficos interactivos con Información relativa a la cantidad de mujeres distribuidas según el rango de distancia a los diferentes establecimientos de utilidad: Centros de Salud; Carabineros; Establecimientos de Educación Parvularia, Básica y Media; y otros sitios de interés de la población. La información es obtenida con base en análisis de imágenes satelitales e información del Censo para los centros urbanos, pueblos y localidades de la comuna."));
            Generica.Add(new ContenidoColeccion(240, "Población mayor a 65 años  por Distancia a Servicios", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_TerceraEdad.png", "Recursos humanos reúne gráficos relativos al personal para la gestión eficiente del Municipio; detalla la cantidad de funcionarios según si son o no profesionales, si están a contrata u honorarios, por escalafón directivo o profesional, si están destinados a programas comunitarios o al sector municipal, diferenciados por sexo. Datos procesados y sistematizados, según disponibilidad en el Sistema Nacional de Información Municipal (SINIM) entre los años 2001–2020."));
            Generica.Add(new ContenidoColeccion(240, "Brief Comunal", "/Images/recuadrosweb_briefcomunal.png", "Dashboard resumen de algunos aspectos generales de la comuna que complementan la información entregada en los contenidos de la suscripción. Incluye Datos Generales del Territorio y sus instrumentos de Planificación Territorial Vigentes, Distribución de la Población y Estadísticas Vitales, Datos Socioeconómicos, de Salud, Educación y Delincuencia, entre otra información que describen de forma general al municipio."));
            Generica.Add(new ContenidoColeccion(240, "Medio Ambiente", "/Images/imagen_recuadrosweb_MUNICIOPIO_MedioAmbiente.png", "Medio Ambiente incluye información Climática relacionada con la evolución de la Precipitación, Temperaturas, Evapotranspiración, Humedad del Suelo, Déficit Hídrico e Índice de Sequía. La información es anual, trimestral y mensual (2001 – 2020); incluye las previsiones anuales para el año 2024. Además, incorpora la evolución Diaria, Mensual, Trimestral y Anual de las emisiones de CO, NO₂, SO₂, O₃, Aerosoles y HCHO (todos contaminantes nocivos para la salud de la población). También sus datos advierten de las Amenazas y Riesgos del cambio climático en la Variación del Rendimiento Agropecuario y en la Presencia Histórica (1980 – 2010)  y Futura (2035-2065)  de Flora y Fauna Nativa de Chile. Toda información a nivel comunal."));
            Generica.Add(new ContenidoColeccion(240, "Economía y Desarrollo", "/Images/imagen_recuadrosweb_MUNICIOPIO_EconomiaYDesarrollo.png", "Economía y Desarrollo entrega información de la cantidad y proporción de Empresas y trabajadores por tramo de venta, rubro, sub rubro y contribuyente, entre los años 2005 y 2020. Adicionalmente agrupa información de los Proyectos de Desarrollo relacionados a infraestructura, liderados por el Ministerio de Obras Públicas (MOP) y sus diferentes servicios. También los proyectos de diferentes titulares e índole tramitados en el marco del Servicio de Evaluación Ambiental (SEA). Los proyectos se presentan según estado de ejecución, montos involucrados y los enlaces a su descripciones específica según institución. Incluye los datos existentes desde el año 1992 a la fecha."));
            Generica.Add(new ContenidoColeccion(240, "Contexto Socioeconómico", "/Images/contenidopublico/DATAINGRESOS_CASEN/imagenes_recuadrosweb_ingresos_por_etniaysexo.png", "Destacan las cifras de la evolución de “Ingresos Promedio Mensuales” y la variación porcentual de éstos, entre mujeres y hombres, según  pertenencia a los diferentes pueblos indígenas y según alfabetización, basado en el análisis de datos obtenidos de las encuestas Caracterización Socioeconómica Nacional (CASEN), de los años 2006/2009/2011/2013/2015/2017/2020. "));
            Generica.Add(new ContenidoColeccion(240, "Inmigrantes", " ", "Texto por definir"));

            /************************************Educación****************************************************************************/
            Generica.Add(new ContenidoColeccion("Desempeño de Establecimientos", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_DesempenoEstablecimientos.png", "Las Categorías de Desempeño es una herramienta de evaluación que integra la distribución de los estudiantes en los Niveles de Aprendizaje de las últimas tres evaluaciones SIMCE y los Indicadores de Desarrollo Personal y Social,  los que se ajustan según las Características socioeconómicas de los Estudiantes del establecimiento.  En Desempeño de establecimientos se entrega información de contexto mediante gráficos interactivos de las categorías de Desempeño por establecimiento y los Niveles de aprendizaje según Grupo Socioeconómico a nivel comunal."));
            Generica.Add(new ContenidoColeccion("Evolución puntaje SIMCE", "/Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_EvolucionPuntajeSIMCEComprensionLectura.png", "Destacamos la información de la evolución de puntaje SIMCE de Comprensión de Lectura y de Matemática obtenido entre los años 2015 y 2019, por los diferentes niveles educacionales de 4.º, 6.º, 8.º básico y 2.º medio, detallado por establecimiento. Información a nivel de comuna."));
            Generica.Add(new ContenidoColeccion("Indicadores de Desarrollo Personal y Social", "/Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_IndicadoresDesarrolloPersonalSocial.png", "Destacamos la información de la Evolución de los Indicadores de Desarrollo Personal y Social; específicamente de Autoestima académica y motivación escolar; Clima de convivencia escolar; Participación y formación ciudadana; y Hábitos de vida saludable para el periodo 2014-2019, detallado por establecimientos a nivel comunal. "));
            Generica.Add(new ContenidoColeccion("Mapas Temáticos de la Educación", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_MapasComparativosEducacion.png", "Esta sección contiene un Mapa comparativo de Establecimientos por Dependencia y grupo socioeconómico en niveles de enseñanza; mapas comparativos según desempeño y nivel educacional del año 2019 considerando puntaje promedio en SIMCE de lenguaje y matemática. Incorpora comparativos de número de docentes en aula del año 2018."));
            Generica.Add(new ContenidoColeccion("Matrículas y docentes en Aula", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_EvolucionPuntajeSIMCEmatematica.png", "Destacamos la información de la evolución en la cantidad de matrículas por tipo de Educación entre los años 2004 y 2020 y el número de docentes por aula detallado por establecimiento entre los años 2010y 2018. Información a nivel de comuna."));
            Generica.Add(new ContenidoColeccion("Niveles de Aprendizaje", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_NiveldeAperndizajeAdecuado.png", "Información relacionada con los Niveles de  Aprendizaje obtenidos por los establecimientos Educacionales según los estándares establecidos vinculados a los resultados SIMCE y los Objetivos de las Bases Curriculares de la educación. Información detallada a nivel de comuna y por establecimiento."));
            Generica.Add(new ContenidoColeccion("Panorama Comunal ", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_CaracterizacionEducacionComunalLocalizacionColegios.png", "Resume la información de los establecimientos educacionales por dependencia; la cantidad de matrículas; el número de docentes por aula; los puntajes promedio, máximo y mínimo de las pruebas SIMCE de Lenguaje y Matemática rendidas entre los años 2016 y 2018; y las categorías de Desempeño. Toda la información se entrega a nivel de comuna."));
            Generica.Add(new ContenidoColeccion("Ranking de Establecimientos", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_RankingDeEstablecimientos.png", "Ranking de colegios según evolución de los indicadores de Desarrollo Personal y Social,  Número de docentes por aula, Cantidad de Alumnos Matriculados,  Niveles de Aprendizaje según resultados de pruebas SIMCE de Comprensión de Lectura y Matemática y resultado obtenidos en la PSU – PTU. "));
            Generica.Add(new ContenidoColeccion("Resultados pruebas PSU - PTU", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_ResultadosPruebasPSUptu.png", "Destacamos la información de la evolución de los puntajes obtenidos en la Prueba de Selección Universitaria (PSU)  y la prueba de Transición Universitaria (PTU) (a partir del año 2020), en sus categorías de Comprensión Lectora y Matemática para el periodo comprendido entre los años 2012 y 2020, por establecimiento según dependencia y a nivel comunal."));
            Generica.Add(new ContenidoColeccion("Resumen por Colegio", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_ResumenporColegio.png", "Para cada establecimiento se puede revisar la información resumen de:  Categoría de desempeño para enseñanza básica y media; evolución de cantidad de alumnos matriculados entre los años 2004 y 2020, detallado también por sexo, evolución de la Cantidad de docentes por aula (años 2010 y 2018); Resultado SIMCE; Indicadores de Desarrollo Personal y Social (de Autoestima académica y motivación escolar, Clima de convivencia escolar)"));
            /************************************Ciudades****************************************************************************/
            Generica.Add(new ContenidoColeccion("Distancias a Servicios", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_MapasInteractivosDistanciasServicios.png", "Mapas Interactivos de distancias a servicios reúne una serie mapas interactivos y mapas descargables en formato pdf que detalla la distancia de comunas y pueblos de una ciudad, en particular, a los diferentes establecimientos de utilidad para las personas: Centros de Salud; Carabineros; Establecimientos de Educación Parvularia, Básica y Media; Sitios de Interés Turístico; Monumentos Nacionales y otros sitios de interés de la población. Toda la información se encuentra geolocalizada a nivel de Zona y Manzana."));
            Generica.Add(new ContenidoColeccion("Índices Espectrales", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_IndicesEspectrales.png", "Índices Espectrales, reúne una serie mapas interactivos, mapas descargables y gráficos que detallan información relativa a los Índices de Vegetación (NDVI), Índices de Vegetación Ajustado al Suelo (SAVI) e Índice de Vegetación Enriquecido (EVI); Índices de Suelo Desnudo (BSI) y Temperatura de diferentes centros urbanos a lo largo de Chile, relacionado también con la cantidad de población, mujeres, adultos mayores, niños, viviendas y hogares contabilizados en estos centros. Toda la información se encuentra geolocalizada a nivel de Zona y Manzana."));
            Generica.Add(new ContenidoColeccion("Establecimientos", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_DistanciasServicios.png", "Gráficos interactivos con el resumen de Información relativa a cantidad de habitantes, de mujeres, de niños y de mayores de 65 años, distribuidos según rango de distancia a centros de Salud, Carabineros, establecimientos de Educación Parvularia, Educación Básica y Media y Educación Superior, Monumentos Nacionales, Sitios de Interés Turístico y Poblacional. Esta misma información se entrega considerando la cantidad de Hogares y viviendas. La información es obtenida con base en análisis de imágenes satelitales e información del Censo para las zonas urbanas de distintos pueblos y comunas de las diferentes regiones del país. "));
            Generica.Add(new ContenidoColeccion("Población", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_Poblacion.png", "Gráficos interactivos con Información relativa a la cantidad de personas, distribuidas según el rango de distancia a los diferentes establecimientos de utilidad: Centros de Salud; Carabineros; Establecimientos de Educación Parvularia, Básica y Media; Sitios de Interés Turístico; Monumentos Nacionales y otros sitios de interés de la población. Adicionalmente se detalla la cantidad de personas según el rango de los Índices Espectrales de Temperatura, Índices de Suelo Desnudo (BSI), Índices de Vegetación (NDVI), Índices de Vegetación Ajustado al Suelo (SAVI) e Índice de Vegetación Enriquecido (EVI). La información es obtenida con base en análisis de imágenes satelitales e información del Censo para las zonas urbanas de distintos pueblos y comunas de las diferentes regiones del país."));
            Generica.Add(new ContenidoColeccion("Viviendas", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_Viviendas.png", "Gráficos interactivos con Información relativa a la cantidad de Viviendas distribuidas según el rango de distancia a los diferentes establecimientos de utilidad: Centros de Salud; Carabineros; Establecimientos de Educación Parvularia, Básica y Media; Sitios de Interés Turístico, Monumentos Nacionales y otros sitios de interés de la población. Adicionalmente se detalla la cantidad de viviendas según el rango de los Índices Espectrales de Temperatura, Índices de Suelo Desnudo (BSI), Índices de Vegetación (NDVI), Índices de Vegetación Ajustado al Suelo (SAVI) e Índice de Vegetación Enriquecido (EVI). La información es obtenida con base en análisis de imágenes satelitales e información del Censo para las zonas urbanas de distintos pueblos y comunas de las diferentes regiones del país."));
            Generica.Add(new ContenidoColeccion("Hogares", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_Hogares.png", "Gráficos interactivos con Información relativa a la cantidad de Hogares distribuidos según el rango de distancia a los diferentes establecimientos de utilidad: Centros de Salud; Carabineros; Establecimientos de Educación Parvularia, Básica y Media; Sitios de Interés Turístico, Monumentos Nacionales y otros sitios de interés de la población. Adicionalmente se detalla la cantidad de hogares según el rango de los Índices Espectrales de Temperatura, Índices de Suelo Desnudo (BSI), Índices de Vegetación (NDVI), Índices de Vegetación Ajustado al Suelo (SAVI) e Índice de Vegetación Enriquecido (EVI). La información es obtenida con base en análisis de imágenes satelitales e información del Censo para las zonas urbanas de distintos pueblos y comunas de las diferentes regiones del país."));
            Generica.Add(new ContenidoColeccion("Distribución de Mujeres", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_Mujeres.png", "Gráficos interactivos con Información relativa a la cantidad de mujeres distribuidas según el rango de distancia a los diferentes establecimientos de utilidad: Centros de Salud; Carabineros; Establecimientos de Educación Parvularia, Básica y Media; y otros sitios de interés de la población. La información es obtenida con base en análisis de imágenes satelitales e información del Censo para las zonas urbanas de distintos pueblos y comunas de las diferentes regiones del país."));
            Generica.Add(new ContenidoColeccion("Distribución de Niños", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_Ninos.png", "Gráficos interactivos con Información relativa a la cantidad de niños entre los 0-14 años, distribuidas según el rango de distancia a los diferentes establecimientos de utilidad: Centros de Salud; Establecimientos de Educación Parvularia, Básica, Media y Superior. La información es obtenida con base en análisis de imágenes satelitales e información del Censo para las zonas urbanas de distintos pueblos y comunas de las diferentes regiones del país."));
            Generica.Add(new ContenidoColeccion("Distribución de Tercera Edad", "/Images/imagenes iconos portada coleccion ciudades/recuadrosweb_ciudades_TerceraEdad.png", "Gráficos interactivos con Información relativa a la cantidad de personas de más de 65 años distribuidas según el rango de distancia a los diferentes establecimientos de utilidad: Centros de Salud; Carabineros; Sitios Turísticos y otros sitios de interés de la población. La información es obtenida con base en análisis de imágenes satelitales e información del Censo para las zonas urbanas de distintos pueblos y comunas de las diferentes regiones del país."));
            /************************************Educación Básica y Media****************************************************************************/
            Generica.Add(new ContenidoColeccion("Desempeño de Establecimientos", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_DesempenoEstablecimientos.png", "Las Categorías de Desempeño es una herramienta de evaluación que integra la distribución de los estudiantes en los Niveles de Aprendizaje de las últimas tres evaluaciones SIMCE y los Indicadores de Desarrollo Personal y Social,  los que se ajustan según las Características socioeconómicas de los Estudiantes del establecimiento.  En Desempeño de establecimientos se entrega información de contexto mediante gráficos interactivos de las categorías de Desempeño por establecimiento y los Niveles de aprendizaje según Grupo Socioeconómico a nivel comunal."));
            Generica.Add(new ContenidoColeccion("Evolución puntaje SIMCE", "/Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_EvolucionPuntajeSIMCEComprensionLectura.png", "Destacamos la información de la evolución de puntaje SIMCE de Comprensión de Lectura y de Matemática obtenido entre los años 2015 y 2019, por los diferentes niveles educacionales de 4.º, 6.º, 8.º básico y 2.º medio, detallado por establecimiento. Información a nivel de comuna."));
            Generica.Add(new ContenidoColeccion("Indicadores de Desarrollo Personal y Social", "/Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_IndicadoresDesarrolloPersonalSocial.png", "Destacamos la información de la Evolución de los Indicadores de Desarrollo Personal y Social; específicamente de Autoestima académica y motivación escolar; Clima de convivencia escolar; Participación y formación ciudadana; y Hábitos de vida saludable para el periodo 2014-2019, detallado por establecimientos a nivel comunal. "));
            Generica.Add(new ContenidoColeccion("Mapas Temáticos de la Educación", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_MapasComparativosEducacion.png", "Esta sección contiene un Mapa comparativo de Establecimientos por Dependencia y grupo socioeconómico en niveles de enseñanza; mapas comparativos según desempeño y nivel educacional del año 2019 considerando puntaje promedio en SIMCE de lenguaje y matemática. Incorpora comparativos de número de docentes en aula del año 2018."));
            Generica.Add(new ContenidoColeccion("Matrículas y docentes en Aula", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_EvolucionPuntajeSIMCEmatematica.png", "Destacamos la información de la evolución en la cantidad de matrículas por tipo de Educación entre los años 2004 y 2020 y el número de docentes por aula detallado por establecimiento entre los años 2010y 2018. Información a nivel de comuna."));
            Generica.Add(new ContenidoColeccion("Niveles de Aprendizaje", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_NiveldeAperndizajeAdecuado.png", "Información relacionada con los Niveles de  Aprendizaje obtenidos por los establecimientos Educacionales según los estándares establecidos vinculados a los resultados SIMCE y los Objetivos de las Bases Curriculares de la educación. Información detallada a nivel de comuna y por establecimiento."));
            Generica.Add(new ContenidoColeccion("Panorama Comunal ", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_CaracterizacionEducacionComunalLocalizacionColegios.png", "Resume la información de los establecimientos educacionales por dependencia; la cantidad de matrículas; el número de docentes por aula; los puntajes promedio, máximo y mínimo de las pruebas SIMCE de Lenguaje y Matemática rendidas entre los años 2016 y 2018; y las categorías de Desempeño. Toda la información se entrega a nivel de comuna."));
            Generica.Add(new ContenidoColeccion("Ranking de Establecimientos", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_RankingDeEstablecimientos.png", "Ranking de colegios según evolución de los indicadores de Desarrollo Personal y Social,  Número de docentes por aula, Cantidad de Alumnos Matriculados,  Niveles de Aprendizaje según resultados de pruebas SIMCE de Comprensión de Lectura y Matemática y resultado obtenidos en la PSU – PTU. "));
            Generica.Add(new ContenidoColeccion("Resultados pruebas PSU - PTU", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_ResultadosPruebasPSUptu.png", "Destacamos la información de la evolución de los puntajes obtenidos en la Prueba de Selección Universitaria (PSU)  y la prueba de Transición Universitaria (PTU) (a partir del año 2020), en sus categorías de Comprensión Lectora y Matemática para el periodo comprendido entre los años 2012 y 2020, por establecimiento según dependencia y a nivel comunal."));
            Generica.Add(new ContenidoColeccion("Resumen por Colegio", " /Content/imagenes coleccin educacin/imagen_recuadrosweb_educacion_ResumenporColegio.png", "Para cada establecimiento se puede revisar la información resumen de:  Categoría de desempeño para enseñanza básica y media; evolución de cantidad de alumnos matriculados entre los años 2004 y 2020, detallado también por sexo, evolución de la Cantidad de docentes por aula (años 2010 y 2018); Resultado SIMCE; Indicadores de Desarrollo Personal y Social (de Autoestima académica y motivación escolar, Clima de convivencia escolar)"));
        }
    }

    public class ContenidoColeccion
    {
        public int codigo { get; set; }
        public string nombre { get; set; }
        public string imagen { get; set; }
        public string descripcion { get; set; }

        public ContenidoColeccion(string nombre, string imagen, string descripcion)
        {
            this.nombre = nombre;
            this.imagen = imagen;
            this.descripcion = descripcion;
        }

        public ContenidoColeccion(int codigo, string nombre, string imagen, string descripcion)
        {
            this.codigo = codigo;
            this.nombre = nombre;
            this.imagen = imagen;
            this.descripcion = descripcion;
        }

        public ContenidoColeccion(string nombre)
        {
            this.nombre = nombre;
            this.imagen = "/Content/img/Imagenes_temas_colecciones/recuadrosweb_Agricultura_plantaciones.png";
            this.descripcion = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been" +
                    "the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of" +
                    "type and scrambled it to make a type specimen book. It has survived not only five centuries, but" +
                    "also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in2";
        }

        public ContenidoColeccion(int codigo, string nombre)
        {
            this.codigo = codigo;
            this.nombre = nombre;
            this.imagen = "/Content/img/Imagenes_temas_colecciones/recuadrosweb_Agricultura_plantaciones.png";
            this.descripcion = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been" +
                    "the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of" +
                    "type and scrambled it to make a type specimen book. It has survived not only five centuries, but" +
                    "also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in2";
        }
    }
}