//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONITOR
    {
        public long id { get; set; }
        public string parametro1_id { get; set; }
        public string parametro1 { get; set; }
        public string parametro2_id { get; set; }
        public string parametro2 { get; set; }
        public string parametro3_id { get; set; }
        public string parametro3 { get; set; }
        public string parametro4_id { get; set; }
        public string parametro4 { get; set; }
        public string url_miniatura { get; set; }
        public string url_extendida { get; set; }
        public string id_tabla { get; set; }
        public string aux { get; set; }
        public string aux2 { get; set; }
    }
}
