//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLA_SEMANARIO
    {
        public long id { get; set; }
        public string nombre { get; set; }
        public string url { get; set; }
        public string observacion { get; set; }
        public string detalles { get; set; }
        public string otro { get; set; }
        public string fecha_publicacion { get; set; }
        public string auxiliar { get; set; }
        public string tabla_padre { get; set; }
        public string tabla_id { get; set; }
    }
}
