//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DETAIL
    {
        public long id { get; set; }
        public string user { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string suscripcion { get; set; }
        public string organizacion { get; set; }
        public string user_type { get; set; }
        public string aux1 { get; set; }
        public string aux2 { get; set; }
    }
}
